# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file '调试.ui'
#
# Created: Fri Dec  8 11:46:02 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(812, 481)
        Dialog.setAcceptDrops(False)
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        self.tabWidget.setGeometry(QtCore.QRect(0, 0, 811, 481))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tab_3 = QtWidgets.QWidget()
        self.tab_3.setObjectName("tab_3")
        self.label = QtWidgets.QLabel(self.tab_3)
        self.label.setGeometry(QtCore.QRect(70, 40, 231, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.debug1_5v_v_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_5v_v_textBrowser.setGeometry(QtCore.QRect(100, 100, 91, 31))
        self.debug1_5v_v_textBrowser.setObjectName("debug1_5v_v_textBrowser")
        self.label_2 = QtWidgets.QLabel(self.tab_3)
        self.label_2.setGeometry(QtCore.QRect(40, 110, 51, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.tab_3)
        self.label_3.setGeometry(QtCore.QRect(190, 110, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.debug1_5v_a_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_5v_a_textBrowser.setGeometry(QtCore.QRect(260, 100, 91, 31))
        self.debug1_5v_a_textBrowser.setObjectName("debug1_5v_a_textBrowser")
        self.label_4 = QtWidgets.QLabel(self.tab_3)
        self.label_4.setGeometry(QtCore.QRect(350, 110, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.debug1_f15v_v_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_f15v_v_textBrowser.setGeometry(QtCore.QRect(100, 180, 91, 31))
        self.debug1_f15v_v_textBrowser.setObjectName("debug1_f15v_v_textBrowser")
        self.debug1_f15v_a_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_f15v_a_textBrowser.setGeometry(QtCore.QRect(260, 180, 91, 31))
        self.debug1_f15v_a_textBrowser.setObjectName("debug1_f15v_a_textBrowser")
        self.label_9 = QtWidgets.QLabel(self.tab_3)
        self.label_9.setGeometry(QtCore.QRect(350, 190, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(self.tab_3)
        self.label_10.setGeometry(QtCore.QRect(20, 190, 61, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.tab_3)
        self.label_11.setGeometry(QtCore.QRect(190, 190, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.debug1_15v_v_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_15v_v_textBrowser.setGeometry(QtCore.QRect(100, 260, 91, 31))
        self.debug1_15v_v_textBrowser.setObjectName("debug1_15v_v_textBrowser")
        self.debug1_15v_a_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_15v_a_textBrowser.setGeometry(QtCore.QRect(260, 260, 91, 31))
        self.debug1_15v_a_textBrowser.setObjectName("debug1_15v_a_textBrowser")
        self.label_12 = QtWidgets.QLabel(self.tab_3)
        self.label_12.setGeometry(QtCore.QRect(350, 270, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.tab_3)
        self.label_13.setGeometry(QtCore.QRect(30, 270, 51, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.tab_3)
        self.label_14.setGeometry(QtCore.QRect(190, 270, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_14.setFont(font)
        self.label_14.setObjectName("label_14")
        self.debug1_24v_v_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_24v_v_textBrowser.setGeometry(QtCore.QRect(100, 340, 91, 31))
        self.debug1_24v_v_textBrowser.setObjectName("debug1_24v_v_textBrowser")
        self.debug1_24v_a_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_24v_a_textBrowser.setGeometry(QtCore.QRect(260, 340, 91, 31))
        self.debug1_24v_a_textBrowser.setObjectName("debug1_24v_a_textBrowser")
        self.label_15 = QtWidgets.QLabel(self.tab_3)
        self.label_15.setGeometry(QtCore.QRect(350, 350, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.label_16 = QtWidgets.QLabel(self.tab_3)
        self.label_16.setGeometry(QtCore.QRect(30, 350, 51, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(20)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.label_17 = QtWidgets.QLabel(self.tab_3)
        self.label_17.setGeometry(QtCore.QRect(190, 350, 31, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_17.setFont(font)
        self.label_17.setObjectName("label_17")
        self.line = QtWidgets.QFrame(self.tab_3)
        self.line.setGeometry(QtCore.QRect(402, 0, 21, 461))
        self.line.setFrameShape(QtWidgets.QFrame.VLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.label_31 = QtWidgets.QLabel(self.tab_3)
        self.label_31.setGeometry(QtCore.QRect(440, 290, 111, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_31.setFont(font)
        self.label_31.setObjectName("label_31")
        self.debug1_shibiema_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_shibiema_textBrowser.setGeometry(QtCore.QRect(450, 330, 231, 31))
        self.debug1_shibiema_textBrowser.setObjectName("debug1_shibiema_textBrowser")
        self.line_2 = QtWidgets.QFrame(self.tab_3)
        self.line_2.setGeometry(QtCore.QRect(410, 200, 401, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.label_59 = QtWidgets.QLabel(self.tab_3)
        self.label_59.setGeometry(QtCore.QRect(440, 20, 151, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_59.setFont(font)
        self.label_59.setObjectName("label_59")
        self.label_60 = QtWidgets.QLabel(self.tab_3)
        self.label_60.setGeometry(QtCore.QRect(440, 70, 151, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_60.setFont(font)
        self.label_60.setObjectName("label_60")
        self.label_61 = QtWidgets.QLabel(self.tab_3)
        self.label_61.setGeometry(QtCore.QRect(440, 110, 151, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_61.setFont(font)
        self.label_61.setObjectName("label_61")
        self.label_62 = QtWidgets.QLabel(self.tab_3)
        self.label_62.setGeometry(QtCore.QRect(445, 150, 151, 21))
        font = QtGui.QFont()
        font.setFamily("幼圆")
        font.setPointSize(14)
        self.label_62.setFont(font)
        self.label_62.setObjectName("label_62")
        self.debug1_Dmodul_check_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_Dmodul_check_textBrowser.setGeometry(QtCore.QRect(530, 65, 121, 31))
        self.debug1_Dmodul_check_textBrowser.setObjectName("debug1_Dmodul_check_textBrowser")
        self.debug1_Amodul_check_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_Amodul_check_textBrowser.setGeometry(QtCore.QRect(530, 105, 121, 31))
        self.debug1_Amodul_check_textBrowser.setObjectName("debug1_Amodul_check_textBrowser")
        self.debug1_PLC_check_textBrowser = QtWidgets.QTextBrowser(self.tab_3)
        self.debug1_PLC_check_textBrowser.setGeometry(QtCore.QRect(530, 145, 121, 31))
        self.debug1_PLC_check_textBrowser.setObjectName("debug1_PLC_check_textBrowser")
        self.tabWidget.addTab(self.tab_3, "")
        self.tab_4 = QtWidgets.QWidget()
        self.tab_4.setObjectName("tab_4")
        self.debug2_ch7_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch7_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 360, 151, 31))
        self.debug2_ch7_coldside_T_textBrowser.setObjectName("debug2_ch7_coldside_T_textBrowser")
        self.debug2_ch6_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch6_Dev_textBrowser.setGeometry(QtCore.QRect(470, 320, 151, 31))
        self.debug2_ch6_Dev_textBrowser.setObjectName("debug2_ch6_Dev_textBrowser")
        self.debug2_ch4_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch4_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 240, 151, 31))
        self.debug2_ch4_coldside_T_textBrowser.setObjectName("debug2_ch4_coldside_T_textBrowser")
        self.debug2_ch4_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch4_Dev_textBrowser.setGeometry(QtCore.QRect(470, 240, 151, 31))
        self.debug2_ch4_Dev_textBrowser.setObjectName("debug2_ch4_Dev_textBrowser")
        self.debug2_ch6_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch6_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 320, 151, 31))
        self.debug2_ch6_coldside_T_textBrowser.setObjectName("debug2_ch6_coldside_T_textBrowser")
        self.label_33 = QtWidgets.QLabel(self.tab_4)
        self.label_33.setGeometry(QtCore.QRect(220, 160, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_33.setFont(font)
        self.label_33.setObjectName("label_33")
        self.debug2_ch8_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch8_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 400, 151, 31))
        self.debug2_ch8_coldside_T_textBrowser.setObjectName("debug2_ch8_coldside_T_textBrowser")
        self.debug2_ch1_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch1_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 120, 151, 31))
        self.debug2_ch1_coldside_T_textBrowser.setObjectName("debug2_ch1_coldside_T_textBrowser")
        self.debug2_ch8_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch8_Dev_textBrowser.setGeometry(QtCore.QRect(470, 400, 151, 31))
        self.debug2_ch8_Dev_textBrowser.setObjectName("debug2_ch8_Dev_textBrowser")
        self.debug2_ch2_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch2_Dev_textBrowser.setGeometry(QtCore.QRect(470, 160, 151, 31))
        self.debug2_ch2_Dev_textBrowser.setObjectName("debug2_ch2_Dev_textBrowser")
        self.label_34 = QtWidgets.QLabel(self.tab_4)
        self.label_34.setGeometry(QtCore.QRect(220, 200, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_34.setFont(font)
        self.label_34.setObjectName("label_34")
        self.label_35 = QtWidgets.QLabel(self.tab_4)
        self.label_35.setGeometry(QtCore.QRect(290, 30, 161, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_35.setFont(font)
        self.label_35.setObjectName("label_35")
        self.label_36 = QtWidgets.QLabel(self.tab_4)
        self.label_36.setGeometry(QtCore.QRect(220, 400, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_36.setFont(font)
        self.label_36.setObjectName("label_36")
        self.debug2_infrared_data_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_infrared_data_textBrowser.setGeometry(QtCore.QRect(450, 30, 151, 31))
        self.debug2_infrared_data_textBrowser.setObjectName("debug2_infrared_data_textBrowser")
        self.debug2_ch1_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch1_Dev_textBrowser.setGeometry(QtCore.QRect(470, 120, 151, 31))
        self.debug2_ch1_Dev_textBrowser.setObjectName("debug2_ch1_Dev_textBrowser")
        self.debug2_ch5_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch5_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 280, 151, 31))
        self.debug2_ch5_coldside_T_textBrowser.setObjectName("debug2_ch5_coldside_T_textBrowser")
        self.label_37 = QtWidgets.QLabel(self.tab_4)
        self.label_37.setGeometry(QtCore.QRect(260, 90, 151, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_37.setFont(font)
        self.label_37.setObjectName("label_37")
        self.label_38 = QtWidgets.QLabel(self.tab_4)
        self.label_38.setGeometry(QtCore.QRect(220, 120, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_38.setFont(font)
        self.label_38.setObjectName("label_38")
        self.debug2_ch3_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch3_Dev_textBrowser.setGeometry(QtCore.QRect(470, 200, 151, 31))
        self.debug2_ch3_Dev_textBrowser.setObjectName("debug2_ch3_Dev_textBrowser")
        self.label_39 = QtWidgets.QLabel(self.tab_4)
        self.label_39.setGeometry(QtCore.QRect(220, 240, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_39.setFont(font)
        self.label_39.setObjectName("label_39")
        self.debug2_ch2_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch2_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 160, 151, 31))
        self.debug2_ch2_coldside_T_textBrowser.setObjectName("debug2_ch2_coldside_T_textBrowser")
        self.debug2_ch5_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch5_Dev_textBrowser.setGeometry(QtCore.QRect(470, 280, 151, 31))
        self.debug2_ch5_Dev_textBrowser.setObjectName("debug2_ch5_Dev_textBrowser")
        self.label_40 = QtWidgets.QLabel(self.tab_4)
        self.label_40.setGeometry(QtCore.QRect(220, 280, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_40.setFont(font)
        self.label_40.setObjectName("label_40")
        self.label_41 = QtWidgets.QLabel(self.tab_4)
        self.label_41.setGeometry(QtCore.QRect(220, 360, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_41.setFont(font)
        self.label_41.setObjectName("label_41")
        self.label_42 = QtWidgets.QLabel(self.tab_4)
        self.label_42.setGeometry(QtCore.QRect(220, 320, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_42.setFont(font)
        self.label_42.setObjectName("label_42")
        self.debug2_ch7_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch7_Dev_textBrowser.setGeometry(QtCore.QRect(470, 360, 151, 31))
        self.debug2_ch7_Dev_textBrowser.setObjectName("debug2_ch7_Dev_textBrowser")
        self.debug2_ch3_coldside_T_textBrowser = QtWidgets.QTextBrowser(self.tab_4)
        self.debug2_ch3_coldside_T_textBrowser.setGeometry(QtCore.QRect(260, 200, 151, 31))
        self.debug2_ch3_coldside_T_textBrowser.setObjectName("debug2_ch3_coldside_T_textBrowser")
        self.label_43 = QtWidgets.QLabel(self.tab_4)
        self.label_43.setGeometry(QtCore.QRect(470, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_43.setFont(font)
        self.label_43.setObjectName("label_43")
        self.tabWidget.addTab(self.tab_4, "")
        self.tab_5 = QtWidgets.QWidget()
        self.tab_5.setObjectName("tab_5")
        self.debug3_ch1_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch1_analog_textBrowser.setGeometry(QtCore.QRect(400, 130, 121, 31))
        self.debug3_ch1_analog_textBrowser.setObjectName("debug3_ch1_analog_textBrowser")
        self.debug3_ch1_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch1_Dev_textBrowser.setGeometry(QtCore.QRect(710, 130, 81, 31))
        self.debug3_ch1_Dev_textBrowser.setObjectName("debug3_ch1_Dev_textBrowser")
        self.debug3_ch2_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch2_Dev_textBrowser.setGeometry(QtCore.QRect(710, 170, 81, 31))
        self.debug3_ch2_Dev_textBrowser.setObjectName("debug3_ch2_Dev_textBrowser")
        self.debug3_ch2_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch2_analog_textBrowser.setGeometry(QtCore.QRect(400, 170, 121, 31))
        self.debug3_ch2_analog_textBrowser.setObjectName("debug3_ch2_analog_textBrowser")
        self.debug3_ch3_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch3_analog_textBrowser.setGeometry(QtCore.QRect(400, 210, 121, 31))
        self.debug3_ch3_analog_textBrowser.setObjectName("debug3_ch3_analog_textBrowser")
        self.debug3_ch3_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch3_Dev_textBrowser.setGeometry(QtCore.QRect(710, 210, 81, 31))
        self.debug3_ch3_Dev_textBrowser.setObjectName("debug3_ch3_Dev_textBrowser")
        self.debug3_ch4_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch4_Dev_textBrowser.setGeometry(QtCore.QRect(710, 250, 81, 31))
        self.debug3_ch4_Dev_textBrowser.setObjectName("debug3_ch4_Dev_textBrowser")
        self.debug3_ch6_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch6_analog_textBrowser.setGeometry(QtCore.QRect(400, 330, 121, 31))
        self.debug3_ch6_analog_textBrowser.setObjectName("debug3_ch6_analog_textBrowser")
        self.debug3_ch5_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch5_Dev_textBrowser.setGeometry(QtCore.QRect(710, 290, 81, 31))
        self.debug3_ch5_Dev_textBrowser.setObjectName("debug3_ch5_Dev_textBrowser")
        self.debug3_ch5_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch5_analog_textBrowser.setGeometry(QtCore.QRect(400, 290, 121, 31))
        self.debug3_ch5_analog_textBrowser.setObjectName("debug3_ch5_analog_textBrowser")
        self.debug3_ch4_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch4_analog_textBrowser.setGeometry(QtCore.QRect(400, 250, 121, 31))
        self.debug3_ch4_analog_textBrowser.setObjectName("debug3_ch4_analog_textBrowser")
        self.debug3_ch6_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch6_Dev_textBrowser.setGeometry(QtCore.QRect(710, 330, 81, 31))
        self.debug3_ch6_Dev_textBrowser.setObjectName("debug3_ch6_Dev_textBrowser")
        self.debug3_ch7_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch7_Dev_textBrowser.setGeometry(QtCore.QRect(710, 370, 81, 31))
        self.debug3_ch7_Dev_textBrowser.setObjectName("debug3_ch7_Dev_textBrowser")
        self.debug3_ch7_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch7_analog_textBrowser.setGeometry(QtCore.QRect(400, 370, 121, 31))
        self.debug3_ch7_analog_textBrowser.setObjectName("debug3_ch7_analog_textBrowser")
        self.debug3_ch3_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch3_translate_textBrowser.setGeometry(QtCore.QRect(550, 210, 121, 31))
        self.debug3_ch3_translate_textBrowser.setObjectName("debug3_ch3_translate_textBrowser")
        self.debug3_ch6_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch6_translate_textBrowser.setGeometry(QtCore.QRect(550, 330, 121, 31))
        self.debug3_ch6_translate_textBrowser.setObjectName("debug3_ch6_translate_textBrowser")
        self.debug3_ch5_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch5_translate_textBrowser.setGeometry(QtCore.QRect(550, 290, 121, 31))
        self.debug3_ch5_translate_textBrowser.setObjectName("debug3_ch5_translate_textBrowser")
        self.debug3_ch2_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch2_translate_textBrowser.setGeometry(QtCore.QRect(550, 170, 121, 31))
        self.debug3_ch2_translate_textBrowser.setObjectName("debug3_ch2_translate_textBrowser")
        self.debug3_ch4_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch4_translate_textBrowser.setGeometry(QtCore.QRect(550, 250, 121, 31))
        self.debug3_ch4_translate_textBrowser.setObjectName("debug3_ch4_translate_textBrowser")
        self.debug3_ch1_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch1_translate_textBrowser.setGeometry(QtCore.QRect(550, 130, 121, 31))
        self.debug3_ch1_translate_textBrowser.setObjectName("debug3_ch1_translate_textBrowser")
        self.debug3_ch7_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch7_translate_textBrowser.setGeometry(QtCore.QRect(550, 370, 121, 31))
        self.debug3_ch7_translate_textBrowser.setObjectName("debug3_ch7_translate_textBrowser")
        self.label_44 = QtWidgets.QLabel(self.tab_5)
        self.label_44.setGeometry(QtCore.QRect(380, 90, 131, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_44.setFont(font)
        self.label_44.setObjectName("label_44")
        self.line_3 = QtWidgets.QFrame(self.tab_5)
        self.line_3.setGeometry(QtCore.QRect(330, 0, 20, 461))
        self.line_3.setFrameShape(QtWidgets.QFrame.VLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.label_52 = QtWidgets.QLabel(self.tab_5)
        self.label_52.setGeometry(QtCore.QRect(360, 290, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_52.setFont(font)
        self.label_52.setObjectName("label_52")
        self.label_50 = QtWidgets.QLabel(self.tab_5)
        self.label_50.setGeometry(QtCore.QRect(360, 210, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_50.setFont(font)
        self.label_50.setObjectName("label_50")
        self.label_48 = QtWidgets.QLabel(self.tab_5)
        self.label_48.setGeometry(QtCore.QRect(360, 330, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_48.setFont(font)
        self.label_48.setObjectName("label_48")
        self.label_45 = QtWidgets.QLabel(self.tab_5)
        self.label_45.setGeometry(QtCore.QRect(360, 250, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_45.setFont(font)
        self.label_45.setObjectName("label_45")
        self.label_49 = QtWidgets.QLabel(self.tab_5)
        self.label_49.setGeometry(QtCore.QRect(360, 130, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_49.setFont(font)
        self.label_49.setObjectName("label_49")
        self.label_51 = QtWidgets.QLabel(self.tab_5)
        self.label_51.setGeometry(QtCore.QRect(360, 370, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_51.setFont(font)
        self.label_51.setObjectName("label_51")
        self.label_47 = QtWidgets.QLabel(self.tab_5)
        self.label_47.setGeometry(QtCore.QRect(360, 410, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_47.setFont(font)
        self.label_47.setObjectName("label_47")
        self.label_46 = QtWidgets.QLabel(self.tab_5)
        self.label_46.setGeometry(QtCore.QRect(360, 170, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_46.setFont(font)
        self.label_46.setObjectName("label_46")
        self.debug3_ch8_Dev_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch8_Dev_textBrowser.setGeometry(QtCore.QRect(710, 410, 81, 31))
        self.debug3_ch8_Dev_textBrowser.setObjectName("debug3_ch8_Dev_textBrowser")
        self.debug3_ch8_analog_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch8_analog_textBrowser.setGeometry(QtCore.QRect(400, 410, 121, 31))
        self.debug3_ch8_analog_textBrowser.setObjectName("debug3_ch8_analog_textBrowser")
        self.debug3_ch8_translate_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_ch8_translate_textBrowser.setGeometry(QtCore.QRect(550, 410, 121, 31))
        self.debug3_ch8_translate_textBrowser.setObjectName("debug3_ch8_translate_textBrowser")
        self.label_53 = QtWidgets.QLabel(self.tab_5)
        self.label_53.setGeometry(QtCore.QRect(540, 90, 141, 31))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_53.setFont(font)
        self.label_53.setObjectName("label_53")
        self.label_54 = QtWidgets.QLabel(self.tab_5)
        self.label_54.setGeometry(QtCore.QRect(705, 90, 101, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_54.setFont(font)
        self.label_54.setObjectName("label_54")
        self.groupBox = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox.setGeometry(QtCore.QRect(10, 10, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox.setFont(font)
        self.groupBox.setObjectName("groupBox")
        self.debug3_type_ADI_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_ADI_radioButton.setGeometry(QtCore.QRect(20, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_ADI_radioButton.setFont(font)
        self.debug3_type_ADI_radioButton.setObjectName("debug3_type_ADI_radioButton")
        self.debug3_type_DAI_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_DAI_radioButton.setGeometry(QtCore.QRect(90, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_DAI_radioButton.setFont(font)
        self.debug3_type_DAI_radioButton.setObjectName("debug3_type_DAI_radioButton")
        self.debug3_type_ADV_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_ADV_radioButton.setGeometry(QtCore.QRect(160, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_ADV_radioButton.setFont(font)
        self.debug3_type_ADV_radioButton.setObjectName("debug3_type_ADV_radioButton")
        self.debug3_type_DAV_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_DAV_radioButton.setGeometry(QtCore.QRect(230, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_DAV_radioButton.setFont(font)
        self.debug3_type_DAV_radioButton.setObjectName("debug3_type_DAV_radioButton")
        self.debug3_type_NTC_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_NTC_radioButton.setGeometry(QtCore.QRect(230, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_NTC_radioButton.setFont(font)
        self.debug3_type_NTC_radioButton.setObjectName("debug3_type_NTC_radioButton")
        self.debug3_type_TCV_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_TCV_radioButton.setGeometry(QtCore.QRect(90, 80, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_TCV_radioButton.setFont(font)
        self.debug3_type_TCV_radioButton.setObjectName("debug3_type_TCV_radioButton")
        self.debug3_type_TCR_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_TCR_radioButton.setGeometry(QtCore.QRect(160, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_TCR_radioButton.setFont(font)
        self.debug3_type_TCR_radioButton.setObjectName("debug3_type_TCR_radioButton")
        self.debug3_type_PT_radioButton = QtWidgets.QRadioButton(self.groupBox)
        self.debug3_type_PT_radioButton.setGeometry(QtCore.QRect(20, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_type_PT_radioButton.setFont(font)
        self.debug3_type_PT_radioButton.setObjectName("debug3_type_PT_radioButton")
        self.groupBox_2 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_2.setGeometry(QtCore.QRect(10, 160, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_2.setFont(font)
        self.groupBox_2.setObjectName("groupBox_2")
        self.debug3_ch1_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch1_radioButton.setGeometry(QtCore.QRect(20, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch1_radioButton.setFont(font)
        self.debug3_ch1_radioButton.setObjectName("debug3_ch1_radioButton")
        self.debug3_ch2_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch2_radioButton.setGeometry(QtCore.QRect(90, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch2_radioButton.setFont(font)
        self.debug3_ch2_radioButton.setObjectName("debug3_ch2_radioButton")
        self.debug3_ch3_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch3_radioButton.setGeometry(QtCore.QRect(160, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch3_radioButton.setFont(font)
        self.debug3_ch3_radioButton.setObjectName("debug3_ch3_radioButton")
        self.debug3_ch4_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch4_radioButton.setGeometry(QtCore.QRect(230, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch4_radioButton.setFont(font)
        self.debug3_ch4_radioButton.setObjectName("debug3_ch4_radioButton")
        self.debug3_ch8_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch8_radioButton.setGeometry(QtCore.QRect(230, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch8_radioButton.setFont(font)
        self.debug3_ch8_radioButton.setObjectName("debug3_ch8_radioButton")
        self.debug3_ch6_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch6_radioButton.setGeometry(QtCore.QRect(90, 80, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch6_radioButton.setFont(font)
        self.debug3_ch6_radioButton.setObjectName("debug3_ch6_radioButton")
        self.debug3_ch7_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch7_radioButton.setGeometry(QtCore.QRect(160, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch7_radioButton.setFont(font)
        self.debug3_ch7_radioButton.setObjectName("debug3_ch7_radioButton")
        self.debug3_ch5_radioButton = QtWidgets.QRadioButton(self.groupBox_2)
        self.debug3_ch5_radioButton.setGeometry(QtCore.QRect(20, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_ch5_radioButton.setFont(font)
        self.debug3_ch5_radioButton.setObjectName("debug3_ch5_radioButton")
        self.groupBox_3 = QtWidgets.QGroupBox(self.tab_5)
        self.groupBox_3.setGeometry(QtCore.QRect(10, 310, 321, 121))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.groupBox_3.setFont(font)
        self.groupBox_3.setObjectName("groupBox_3")
        self.debug3_gain_1_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.debug3_gain_1_radioButton.setGeometry(QtCore.QRect(30, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_gain_1_radioButton.setFont(font)
        self.debug3_gain_1_radioButton.setObjectName("debug3_gain_1_radioButton")
        self.debug3_gain_8_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.debug3_gain_8_radioButton.setGeometry(QtCore.QRect(110, 40, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_gain_8_radioButton.setFont(font)
        self.debug3_gain_8_radioButton.setObjectName("debug3_gain_8_radioButton")
        self.debug3_gain_16_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.debug3_gain_16_radioButton.setGeometry(QtCore.QRect(190, 40, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_gain_16_radioButton.setFont(font)
        self.debug3_gain_16_radioButton.setObjectName("debug3_gain_16_radioButton")
        self.debug3_gain_32_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.debug3_gain_32_radioButton.setGeometry(QtCore.QRect(30, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_gain_32_radioButton.setFont(font)
        self.debug3_gain_32_radioButton.setObjectName("debug3_gain_32_radioButton")
        self.debug3_gain_128_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.debug3_gain_128_radioButton.setGeometry(QtCore.QRect(190, 80, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_gain_128_radioButton.setFont(font)
        self.debug3_gain_128_radioButton.setObjectName("debug3_gain_128_radioButton")
        self.debug3_gain_64_radioButton = QtWidgets.QRadioButton(self.groupBox_3)
        self.debug3_gain_64_radioButton.setGeometry(QtCore.QRect(110, 80, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(13)
        self.debug3_gain_64_radioButton.setFont(font)
        self.debug3_gain_64_radioButton.setObjectName("debug3_gain_64_radioButton")
        self.line_4 = QtWidgets.QFrame(self.tab_5)
        self.line_4.setGeometry(QtCore.QRect(340, 80, 471, 16))
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.label_55 = QtWidgets.QLabel(self.tab_5)
        self.label_55.setGeometry(QtCore.QRect(360, 25, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_55.setFont(font)
        self.label_55.setObjectName("label_55")
        self.debug3_BFM27_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_BFM27_textBrowser.setGeometry(QtCore.QRect(440, 25, 121, 31))
        self.debug3_BFM27_textBrowser.setObjectName("debug3_BFM27_textBrowser")
        self.label_56 = QtWidgets.QLabel(self.tab_5)
        self.label_56.setGeometry(QtCore.QRect(590, 25, 71, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_56.setFont(font)
        self.label_56.setObjectName("label_56")
        self.debug3_BFM67_textBrowser = QtWidgets.QTextBrowser(self.tab_5)
        self.debug3_BFM67_textBrowser.setGeometry(QtCore.QRect(670, 25, 121, 31))
        self.debug3_BFM67_textBrowser.setObjectName("debug3_BFM67_textBrowser")
        self.tabWidget.addTab(self.tab_5, "")
        self.tab_6 = QtWidgets.QWidget()
        self.tab_6.setObjectName("tab_6")
        self.debug4_Y0_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y0_checkBox.setGeometry(QtCore.QRect(170, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y0_checkBox.setFont(font)
        self.debug4_Y0_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y0_checkBox.setObjectName("debug4_Y0_checkBox")
        self.debug4_Y1_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y1_checkBox.setGeometry(QtCore.QRect(230, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y1_checkBox.setFont(font)
        self.debug4_Y1_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y1_checkBox.setObjectName("debug4_Y1_checkBox")
        self.debug4_Y2_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y2_checkBox.setGeometry(QtCore.QRect(290, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y2_checkBox.setFont(font)
        self.debug4_Y2_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y2_checkBox.setObjectName("debug4_Y2_checkBox")
        self.debug4_Y3_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y3_checkBox.setGeometry(QtCore.QRect(350, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y3_checkBox.setFont(font)
        self.debug4_Y3_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y3_checkBox.setObjectName("debug4_Y3_checkBox")
        self.debug4_Y4_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y4_checkBox.setGeometry(QtCore.QRect(410, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y4_checkBox.setFont(font)
        self.debug4_Y4_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y4_checkBox.setObjectName("debug4_Y4_checkBox")
        self.debug4_Y5_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y5_checkBox.setGeometry(QtCore.QRect(470, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y5_checkBox.setFont(font)
        self.debug4_Y5_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y5_checkBox.setObjectName("debug4_Y5_checkBox")
        self.debug4_Y6_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y6_checkBox.setGeometry(QtCore.QRect(530, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y6_checkBox.setFont(font)
        self.debug4_Y6_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y6_checkBox.setObjectName("debug4_Y6_checkBox")
        self.debug4_Y7_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y7_checkBox.setGeometry(QtCore.QRect(590, 130, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y7_checkBox.setFont(font)
        self.debug4_Y7_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y7_checkBox.setObjectName("debug4_Y7_checkBox")
        self.debug4_X1_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X1_checkBox.setGeometry(QtCore.QRect(230, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X1_checkBox.setFont(font)
        self.debug4_X1_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X1_checkBox.setObjectName("debug4_X1_checkBox")
        self.debug4_X0_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X0_checkBox.setGeometry(QtCore.QRect(170, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X0_checkBox.setFont(font)
        self.debug4_X0_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X0_checkBox.setObjectName("debug4_X0_checkBox")
        self.debug4_X4_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X4_checkBox.setGeometry(QtCore.QRect(410, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X4_checkBox.setFont(font)
        self.debug4_X4_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X4_checkBox.setObjectName("debug4_X4_checkBox")
        self.debug4_X2_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X2_checkBox.setGeometry(QtCore.QRect(290, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X2_checkBox.setFont(font)
        self.debug4_X2_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X2_checkBox.setObjectName("debug4_X2_checkBox")
        self.debug4_X3_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X3_checkBox.setGeometry(QtCore.QRect(350, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X3_checkBox.setFont(font)
        self.debug4_X3_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X3_checkBox.setObjectName("debug4_X3_checkBox")
        self.debug4_X6_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X6_checkBox.setGeometry(QtCore.QRect(530, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X6_checkBox.setFont(font)
        self.debug4_X6_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X6_checkBox.setObjectName("debug4_X6_checkBox")
        self.debug4_X5_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X5_checkBox.setGeometry(QtCore.QRect(470, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X5_checkBox.setFont(font)
        self.debug4_X5_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X5_checkBox.setObjectName("debug4_X5_checkBox")
        self.debug4_X7_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X7_checkBox.setGeometry(QtCore.QRect(590, 170, 41, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X7_checkBox.setFont(font)
        self.debug4_X7_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X7_checkBox.setAcceptDrops(False)
        self.debug4_X7_checkBox.setObjectName("debug4_X7_checkBox")
        self.debug4_Y14_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y14_checkBox.setGeometry(QtCore.QRect(410, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y14_checkBox.setFont(font)
        self.debug4_Y14_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y14_checkBox.setObjectName("debug4_Y14_checkBox")
        self.debug4_Y13_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y13_checkBox.setGeometry(QtCore.QRect(350, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y13_checkBox.setFont(font)
        self.debug4_Y13_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y13_checkBox.setObjectName("debug4_Y13_checkBox")
        self.debug4_Y12_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y12_checkBox.setGeometry(QtCore.QRect(290, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y12_checkBox.setFont(font)
        self.debug4_Y12_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y12_checkBox.setObjectName("debug4_Y12_checkBox")
        self.debug4_Y11_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y11_checkBox.setGeometry(QtCore.QRect(230, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y11_checkBox.setFont(font)
        self.debug4_Y11_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y11_checkBox.setObjectName("debug4_Y11_checkBox")
        self.debug4_Y17_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y17_checkBox.setGeometry(QtCore.QRect(590, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y17_checkBox.setFont(font)
        self.debug4_Y17_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y17_checkBox.setObjectName("debug4_Y17_checkBox")
        self.debug4_Y16_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y16_checkBox.setGeometry(QtCore.QRect(530, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y16_checkBox.setFont(font)
        self.debug4_Y16_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y16_checkBox.setObjectName("debug4_Y16_checkBox")
        self.debug4_Y15_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y15_checkBox.setGeometry(QtCore.QRect(470, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y15_checkBox.setFont(font)
        self.debug4_Y15_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y15_checkBox.setObjectName("debug4_Y15_checkBox")
        self.debug4_Y10_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_Y10_checkBox.setGeometry(QtCore.QRect(170, 240, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_Y10_checkBox.setFont(font)
        self.debug4_Y10_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_Y10_checkBox.setObjectName("debug4_Y10_checkBox")
        self.debug4_X15_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X15_checkBox.setGeometry(QtCore.QRect(470, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X15_checkBox.setFont(font)
        self.debug4_X15_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X15_checkBox.setObjectName("debug4_X15_checkBox")
        self.debug4_X17_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X17_checkBox.setGeometry(QtCore.QRect(590, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X17_checkBox.setFont(font)
        self.debug4_X17_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X17_checkBox.setObjectName("debug4_X17_checkBox")
        self.debug4_X13_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X13_checkBox.setGeometry(QtCore.QRect(350, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X13_checkBox.setFont(font)
        self.debug4_X13_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X13_checkBox.setObjectName("debug4_X13_checkBox")
        self.debug4_X14_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X14_checkBox.setGeometry(QtCore.QRect(410, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X14_checkBox.setFont(font)
        self.debug4_X14_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X14_checkBox.setObjectName("debug4_X14_checkBox")
        self.debug4_X10_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X10_checkBox.setGeometry(QtCore.QRect(170, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X10_checkBox.setFont(font)
        self.debug4_X10_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X10_checkBox.setObjectName("debug4_X10_checkBox")
        self.debug4_X12_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X12_checkBox.setGeometry(QtCore.QRect(290, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X12_checkBox.setFont(font)
        self.debug4_X12_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X12_checkBox.setObjectName("debug4_X12_checkBox")
        self.debug4_X11_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X11_checkBox.setGeometry(QtCore.QRect(230, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X11_checkBox.setFont(font)
        self.debug4_X11_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X11_checkBox.setObjectName("debug4_X11_checkBox")
        self.debug4_X16_checkBox = QtWidgets.QCheckBox(self.tab_6)
        self.debug4_X16_checkBox.setGeometry(QtCore.QRect(530, 280, 51, 16))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.debug4_X16_checkBox.setFont(font)
        self.debug4_X16_checkBox.setCursor(QtGui.QCursor(QtCore.Qt.ForbiddenCursor))
        self.debug4_X16_checkBox.setObjectName("debug4_X16_checkBox")
        self.label_57 = QtWidgets.QLabel(self.tab_6)
        self.label_57.setGeometry(QtCore.QRect(330, 50, 101, 51))
        font = QtGui.QFont()
        font.setPointSize(16)
        self.label_57.setFont(font)
        self.label_57.setObjectName("label_57")
        self.tabWidget.addTab(self.tab_6, "")
        self.tab_7 = QtWidgets.QWidget()
        self.tab_7.setObjectName("tab_7")
        self.label_58 = QtWidgets.QLabel(self.tab_7)
        self.label_58.setGeometry(QtCore.QRect(20, 10, 181, 31))
        font = QtGui.QFont()
        font.setPointSize(22)
        self.label_58.setFont(font)
        self.label_58.setObjectName("label_58")
        self.debug5_log_textBrowser = QtWidgets.QTextBrowser(self.tab_7)
        self.debug5_log_textBrowser.setGeometry(QtCore.QRect(20, 40, 771, 411))
        self.debug5_log_textBrowser.setObjectName("debug5_log_textBrowser")
        self.tabWidget.addTab(self.tab_7, "")

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.label.setText(_translate("Dialog", "被测模块电源实际测量值"))
        self.label_2.setText(_translate("Dialog", "5v"))
        self.label_3.setText(_translate("Dialog", "mV"))
        self.label_4.setText(_translate("Dialog", "mA"))
        self.label_9.setText(_translate("Dialog", "mA"))
        self.label_10.setText(_translate("Dialog", "-15v"))
        self.label_11.setText(_translate("Dialog", "mV"))
        self.label_12.setText(_translate("Dialog", "mA"))
        self.label_13.setText(_translate("Dialog", "15v"))
        self.label_14.setText(_translate("Dialog", "mV"))
        self.label_15.setText(_translate("Dialog", "mA"))
        self.label_16.setText(_translate("Dialog", "24v"))
        self.label_17.setText(_translate("Dialog", "mV"))
        self.label_31.setText(_translate("Dialog", "模块识别码："))
        self.label_59.setText(_translate("Dialog", "已连接的设备："))
        self.label_60.setText(_translate("Dialog", "数字模块"))
        self.label_61.setText(_translate("Dialog", "模拟模块"))
        self.label_62.setText(_translate("Dialog", "PLC"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_3), _translate("Dialog", "初始化"))
        self.label_33.setText(_translate("Dialog", "CH2"))
        self.label_34.setText(_translate("Dialog", "CH3"))
        self.label_35.setText(_translate("Dialog", "红外模块温度(℃)"))
        self.label_36.setText(_translate("Dialog", "CH8"))
        self.label_37.setText(_translate("Dialog", "各通道冷端温度(℃)"))
        self.label_38.setText(_translate("Dialog", "CH1"))
        self.label_39.setText(_translate("Dialog", "CH4"))
        self.label_40.setText(_translate("Dialog", "CH5"))
        self.label_41.setText(_translate("Dialog", "CH7"))
        self.label_42.setText(_translate("Dialog", "CH6"))
        self.label_43.setText(_translate("Dialog", "对比差值(℃)"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_4), _translate("Dialog", "冷端温度采集"))
        self.label_44.setText(_translate("Dialog", "模拟输出电压(uv)"))
        self.label_52.setText(_translate("Dialog", "CH5"))
        self.label_50.setText(_translate("Dialog", "CH3"))
        self.label_48.setText(_translate("Dialog", "CH6"))
        self.label_45.setText(_translate("Dialog", "CH4"))
        self.label_49.setText(_translate("Dialog", "CH1"))
        self.label_51.setText(_translate("Dialog", "CH7"))
        self.label_47.setText(_translate("Dialog", "CH8"))
        self.label_46.setText(_translate("Dialog", "CH2"))
        self.label_53.setText(_translate("Dialog", "模块温度转电压值(uv)"))
        self.label_54.setText(_translate("Dialog", "对比误差(uv)"))
        self.groupBox.setTitle(_translate("Dialog", "类型选择"))
        self.debug3_type_ADI_radioButton.setText(_translate("Dialog", "ADI"))
        self.debug3_type_DAI_radioButton.setText(_translate("Dialog", "DAI"))
        self.debug3_type_ADV_radioButton.setText(_translate("Dialog", "ADV"))
        self.debug3_type_DAV_radioButton.setText(_translate("Dialog", "DAV"))
        self.debug3_type_NTC_radioButton.setText(_translate("Dialog", "NTC"))
        self.debug3_type_TCV_radioButton.setText(_translate("Dialog", "TCV"))
        self.debug3_type_TCR_radioButton.setText(_translate("Dialog", "TCR"))
        self.debug3_type_PT_radioButton.setText(_translate("Dialog", "PT"))
        self.groupBox_2.setTitle(_translate("Dialog", "通道选择"))
        self.debug3_ch1_radioButton.setText(_translate("Dialog", "CH1"))
        self.debug3_ch2_radioButton.setText(_translate("Dialog", "CH2"))
        self.debug3_ch3_radioButton.setText(_translate("Dialog", "CH3"))
        self.debug3_ch4_radioButton.setText(_translate("Dialog", "CH4"))
        self.debug3_ch8_radioButton.setText(_translate("Dialog", "CH8"))
        self.debug3_ch6_radioButton.setText(_translate("Dialog", "CH6"))
        self.debug3_ch7_radioButton.setText(_translate("Dialog", "CH7"))
        self.debug3_ch5_radioButton.setText(_translate("Dialog", "CH5"))
        self.groupBox_3.setTitle(_translate("Dialog", "增益设置"))
        self.debug3_gain_1_radioButton.setText(_translate("Dialog", "1"))
        self.debug3_gain_8_radioButton.setText(_translate("Dialog", "8"))
        self.debug3_gain_16_radioButton.setText(_translate("Dialog", "16"))
        self.debug3_gain_32_radioButton.setText(_translate("Dialog", "32"))
        self.debug3_gain_128_radioButton.setText(_translate("Dialog", "128"))
        self.debug3_gain_64_radioButton.setText(_translate("Dialog", "64"))
        self.label_55.setText(_translate("Dialog", "BFM #27值"))
        self.label_56.setText(_translate("Dialog", "BFM #67值"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_5), _translate("Dialog", "热端温度采集"))
        self.debug4_Y0_checkBox.setText(_translate("Dialog", "Y0"))
        self.debug4_Y1_checkBox.setText(_translate("Dialog", "Y1"))
        self.debug4_Y2_checkBox.setText(_translate("Dialog", "Y2"))
        self.debug4_Y3_checkBox.setText(_translate("Dialog", "Y3"))
        self.debug4_Y4_checkBox.setText(_translate("Dialog", "Y4"))
        self.debug4_Y5_checkBox.setText(_translate("Dialog", "Y5"))
        self.debug4_Y6_checkBox.setText(_translate("Dialog", "Y6"))
        self.debug4_Y7_checkBox.setText(_translate("Dialog", "Y7"))
        self.debug4_X1_checkBox.setText(_translate("Dialog", "X1"))
        self.debug4_X0_checkBox.setText(_translate("Dialog", "X0"))
        self.debug4_X4_checkBox.setText(_translate("Dialog", "X4"))
        self.debug4_X2_checkBox.setText(_translate("Dialog", "X2"))
        self.debug4_X3_checkBox.setText(_translate("Dialog", "X3"))
        self.debug4_X6_checkBox.setText(_translate("Dialog", "X6"))
        self.debug4_X5_checkBox.setText(_translate("Dialog", "X5"))
        self.debug4_X7_checkBox.setText(_translate("Dialog", "X7"))
        self.debug4_Y14_checkBox.setText(_translate("Dialog", "Y14"))
        self.debug4_Y13_checkBox.setText(_translate("Dialog", "Y13"))
        self.debug4_Y12_checkBox.setText(_translate("Dialog", "Y12"))
        self.debug4_Y11_checkBox.setText(_translate("Dialog", "Y11"))
        self.debug4_Y17_checkBox.setText(_translate("Dialog", "Y17"))
        self.debug4_Y16_checkBox.setText(_translate("Dialog", "Y16"))
        self.debug4_Y15_checkBox.setText(_translate("Dialog", "Y15"))
        self.debug4_Y10_checkBox.setText(_translate("Dialog", "Y10"))
        self.debug4_X15_checkBox.setText(_translate("Dialog", "X15"))
        self.debug4_X17_checkBox.setText(_translate("Dialog", "X17"))
        self.debug4_X13_checkBox.setText(_translate("Dialog", "X13"))
        self.debug4_X14_checkBox.setText(_translate("Dialog", "X14"))
        self.debug4_X10_checkBox.setText(_translate("Dialog", "X10"))
        self.debug4_X12_checkBox.setText(_translate("Dialog", "X12"))
        self.debug4_X11_checkBox.setText(_translate("Dialog", "X11"))
        self.debug4_X16_checkBox.setText(_translate("Dialog", "X16"))
        self.label_57.setText(_translate("Dialog", "端口测试"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_6), _translate("Dialog", "接线端测试"))
        self.label_58.setText(_translate("Dialog", "日志信息显示"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tab_7), _translate("Dialog", "日志信息"))

