# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_calibration_backstage.ui'
#
# Created: Fri Jul  7 18:50:32 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Calibration_Backstage(object):
    def setupUi(self, widget_Calibration_Backstage):
        widget_Calibration_Backstage.setObjectName("widget_Calibration_Backstage")
        widget_Calibration_Backstage.resize(818, 369)
        self.layoutWidget = QtWidgets.QWidget(widget_Calibration_Backstage)
        self.layoutWidget.setGeometry(QtCore.QRect(8, 88, 801, 265))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_Ch1 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch1.setMinimumSize(QtCore.QSize(86, 0))
        self.label_Ch1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch1.setObjectName("label_Ch1")
        self.gridLayout.addWidget(self.label_Ch1, 0, 0, 1, 1)
        self.lineEdit_00 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_00.setObjectName("lineEdit_00")
        self.gridLayout.addWidget(self.lineEdit_00, 0, 1, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 0, 2, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 0, 3, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout.addWidget(self.lineEdit_30, 0, 4, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout.addWidget(self.lineEdit_40, 0, 5, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout.addWidget(self.lineEdit_50, 0, 6, 1, 1)
        self.lineEdit_60 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_60.setObjectName("lineEdit_60")
        self.gridLayout.addWidget(self.lineEdit_60, 0, 7, 1, 1)
        self.label_Ch1_Result = QtWidgets.QLabel(self.layoutWidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_Ch1_Result.sizePolicy().hasHeightForWidth())
        self.label_Ch1_Result.setSizePolicy(sizePolicy)
        self.label_Ch1_Result.setMinimumSize(QtCore.QSize(83, 0))
        self.label_Ch1_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch1_Result.setObjectName("label_Ch1_Result")
        self.gridLayout.addWidget(self.label_Ch1_Result, 0, 8, 1, 1)
        self.label_Ch2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch2.setObjectName("label_Ch2")
        self.gridLayout.addWidget(self.label_Ch2, 1, 0, 1, 1)
        self.lineEdit_01 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_01.setObjectName("lineEdit_01")
        self.gridLayout.addWidget(self.lineEdit_01, 1, 1, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 1, 2, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 1, 3, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout.addWidget(self.lineEdit_31, 1, 4, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout.addWidget(self.lineEdit_41, 1, 5, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout.addWidget(self.lineEdit_51, 1, 6, 1, 1)
        self.lineEdit_61 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_61.setObjectName("lineEdit_61")
        self.gridLayout.addWidget(self.lineEdit_61, 1, 7, 1, 1)
        self.label_Ch2_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch2_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch2_Result.setObjectName("label_Ch2_Result")
        self.gridLayout.addWidget(self.label_Ch2_Result, 1, 8, 1, 1)
        self.label_Ch3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch3.setObjectName("label_Ch3")
        self.gridLayout.addWidget(self.label_Ch3, 2, 0, 1, 1)
        self.lineEdit_02 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_02.setObjectName("lineEdit_02")
        self.gridLayout.addWidget(self.lineEdit_02, 2, 1, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 2, 2, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 2, 3, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout.addWidget(self.lineEdit_32, 2, 4, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout.addWidget(self.lineEdit_42, 2, 5, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout.addWidget(self.lineEdit_52, 2, 6, 1, 1)
        self.lineEdit_62 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_62.setObjectName("lineEdit_62")
        self.gridLayout.addWidget(self.lineEdit_62, 2, 7, 1, 1)
        self.label_Ch3_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch3_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch3_Result.setObjectName("label_Ch3_Result")
        self.gridLayout.addWidget(self.label_Ch3_Result, 2, 8, 1, 1)
        self.label_Ch4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch4.setObjectName("label_Ch4")
        self.gridLayout.addWidget(self.label_Ch4, 3, 0, 1, 1)
        self.lineEdit_03 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_03.setObjectName("lineEdit_03")
        self.gridLayout.addWidget(self.lineEdit_03, 3, 1, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 3, 2, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 3, 3, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 3, 4, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout.addWidget(self.lineEdit_43, 3, 5, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout.addWidget(self.lineEdit_53, 3, 6, 1, 1)
        self.lineEdit_63 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_63.setObjectName("lineEdit_63")
        self.gridLayout.addWidget(self.lineEdit_63, 3, 7, 1, 1)
        self.label_Ch4_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch4_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch4_Result.setObjectName("label_Ch4_Result")
        self.gridLayout.addWidget(self.label_Ch4_Result, 3, 8, 1, 1)
        self.label_Ch5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch5.setObjectName("label_Ch5")
        self.gridLayout.addWidget(self.label_Ch5, 4, 0, 1, 1)
        self.lineEdit_04 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_04.setObjectName("lineEdit_04")
        self.gridLayout.addWidget(self.lineEdit_04, 4, 1, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 4, 2, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout.addWidget(self.lineEdit_24, 4, 3, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout.addWidget(self.lineEdit_34, 4, 4, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout.addWidget(self.lineEdit_44, 4, 5, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout.addWidget(self.lineEdit_54, 4, 6, 1, 1)
        self.lineEdit_64 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_64.setObjectName("lineEdit_64")
        self.gridLayout.addWidget(self.lineEdit_64, 4, 7, 1, 1)
        self.label_Ch5_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch5_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch5_Result.setObjectName("label_Ch5_Result")
        self.gridLayout.addWidget(self.label_Ch5_Result, 4, 8, 1, 1)
        self.label_Ch6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch6.setObjectName("label_Ch6")
        self.gridLayout.addWidget(self.label_Ch6, 5, 0, 1, 1)
        self.lineEdit_05 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_05.setObjectName("lineEdit_05")
        self.gridLayout.addWidget(self.lineEdit_05, 5, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 5, 2, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 5, 3, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout.addWidget(self.lineEdit_35, 5, 4, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout.addWidget(self.lineEdit_45, 5, 5, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout.addWidget(self.lineEdit_55, 5, 6, 1, 1)
        self.lineEdit_65 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_65.setObjectName("lineEdit_65")
        self.gridLayout.addWidget(self.lineEdit_65, 5, 7, 1, 1)
        self.label_Ch6_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch6_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch6_Result.setObjectName("label_Ch6_Result")
        self.gridLayout.addWidget(self.label_Ch6_Result, 5, 8, 1, 1)
        self.label_Ch7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch7.setObjectName("label_Ch7")
        self.gridLayout.addWidget(self.label_Ch7, 6, 0, 1, 1)
        self.lineEdit_06 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_06.setObjectName("lineEdit_06")
        self.gridLayout.addWidget(self.lineEdit_06, 6, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 6, 2, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout.addWidget(self.lineEdit_26, 6, 3, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout.addWidget(self.lineEdit_36, 6, 4, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout.addWidget(self.lineEdit_46, 6, 5, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout.addWidget(self.lineEdit_56, 6, 6, 1, 1)
        self.lineEdit_66 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_66.setObjectName("lineEdit_66")
        self.gridLayout.addWidget(self.lineEdit_66, 6, 7, 1, 1)
        self.label_Ch7_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch7_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch7_Result.setObjectName("label_Ch7_Result")
        self.gridLayout.addWidget(self.label_Ch7_Result, 6, 8, 1, 1)
        self.label_Ch8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch8.setObjectName("label_Ch8")
        self.gridLayout.addWidget(self.label_Ch8, 7, 0, 1, 1)
        self.lineEdit_07 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_07.setObjectName("lineEdit_07")
        self.gridLayout.addWidget(self.lineEdit_07, 7, 1, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 7, 2, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout.addWidget(self.lineEdit_27, 7, 3, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 7, 4, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout.addWidget(self.lineEdit_47, 7, 5, 1, 1)
        self.lineEdit_57 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_57.setObjectName("lineEdit_57")
        self.gridLayout.addWidget(self.lineEdit_57, 7, 6, 1, 1)
        self.lineEdit_67 = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_67.setObjectName("lineEdit_67")
        self.gridLayout.addWidget(self.lineEdit_67, 7, 7, 1, 1)
        self.label_Ch8_Result = QtWidgets.QLabel(self.layoutWidget)
        self.label_Ch8_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch8_Result.setObjectName("label_Ch8_Result")
        self.gridLayout.addWidget(self.label_Ch8_Result, 7, 8, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(widget_Calibration_Backstage)
        self.layoutWidget1.setGeometry(QtCore.QRect(8, 9, 801, 33))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_Ch_Id = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Ch_Id.setMinimumSize(QtCore.QSize(86, 0))
        self.label_Ch_Id.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Ch_Id.setObjectName("label_Ch_Id")
        self.gridLayout_2.addWidget(self.label_Ch_Id, 0, 0, 1, 1)
        self.label_Init = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Init.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Init.setObjectName("label_Init")
        self.gridLayout_2.addWidget(self.label_Init, 0, 1, 1, 1)
        self.label_CaliA = QtWidgets.QLabel(self.layoutWidget1)
        self.label_CaliA.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CaliA.setObjectName("label_CaliA")
        self.gridLayout_2.addWidget(self.label_CaliA, 0, 2, 1, 1)
        self.label_CaliB = QtWidgets.QLabel(self.layoutWidget1)
        self.label_CaliB.setAlignment(QtCore.Qt.AlignCenter)
        self.label_CaliB.setObjectName("label_CaliB")
        self.gridLayout_2.addWidget(self.label_CaliB, 0, 3, 1, 1)
        self.label_Bench1 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Bench1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Bench1.setObjectName("label_Bench1")
        self.gridLayout_2.addWidget(self.label_Bench1, 0, 4, 1, 1)
        self.label_Bench2 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Bench2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Bench2.setObjectName("label_Bench2")
        self.gridLayout_2.addWidget(self.label_Bench2, 0, 5, 1, 1)
        self.label_Bench3 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Bench3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Bench3.setObjectName("label_Bench3")
        self.gridLayout_2.addWidget(self.label_Bench3, 0, 6, 1, 1)
        self.label_Error = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Error.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Error.setObjectName("label_Error")
        self.gridLayout_2.addWidget(self.label_Error, 0, 7, 1, 1)
        self.label_Result = QtWidgets.QLabel(self.layoutWidget1)
        self.label_Result.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Result.setObjectName("label_Result")
        self.gridLayout_2.addWidget(self.label_Result, 0, 8, 1, 1)
        self.layoutWidget2 = QtWidgets.QWidget(widget_Calibration_Backstage)
        self.layoutWidget2.setGeometry(QtCore.QRect(8, 48, 801, 33))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_Unit_Show = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit_Show.setMinimumSize(QtCore.QSize(86, 0))
        self.label_Unit_Show.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit_Show.setObjectName("label_Unit_Show")
        self.gridLayout_4.addWidget(self.label_Unit_Show, 0, 0, 1, 1)
        self.label_Unit1 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit1.setText("")
        self.label_Unit1.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit1.setObjectName("label_Unit1")
        self.gridLayout_4.addWidget(self.label_Unit1, 0, 1, 1, 1)
        self.label_Unit2 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit2.setText("")
        self.label_Unit2.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit2.setObjectName("label_Unit2")
        self.gridLayout_4.addWidget(self.label_Unit2, 0, 2, 1, 1)
        self.label_Unit3 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit3.setText("")
        self.label_Unit3.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit3.setObjectName("label_Unit3")
        self.gridLayout_4.addWidget(self.label_Unit3, 0, 3, 1, 1)
        self.label_Unit4 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit4.setText("")
        self.label_Unit4.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit4.setObjectName("label_Unit4")
        self.gridLayout_4.addWidget(self.label_Unit4, 0, 4, 1, 1)
        self.label_Unit5 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit5.setText("")
        self.label_Unit5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit5.setObjectName("label_Unit5")
        self.gridLayout_4.addWidget(self.label_Unit5, 0, 5, 1, 1)
        self.label_Unit6 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit6.setText("")
        self.label_Unit6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit6.setObjectName("label_Unit6")
        self.gridLayout_4.addWidget(self.label_Unit6, 0, 6, 1, 1)
        self.label_Unit7 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_Unit7.setText("")
        self.label_Unit7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Unit7.setObjectName("label_Unit7")
        self.gridLayout_4.addWidget(self.label_Unit7, 0, 7, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_43.setText("")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 8, 1, 1)

        self.retranslateUi(widget_Calibration_Backstage)
        QtCore.QMetaObject.connectSlotsByName(widget_Calibration_Backstage)

    def retranslateUi(self, widget_Calibration_Backstage):
        _translate = QtCore.QCoreApplication.translate
        widget_Calibration_Backstage.setWindowTitle(_translate("widget_Calibration_Backstage", "Form"))
        self.label_Ch1.setText(_translate("widget_Calibration_Backstage", "CH 1"))
        self.label_Ch1_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch2.setText(_translate("widget_Calibration_Backstage", "CH 2"))
        self.label_Ch2_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch3.setText(_translate("widget_Calibration_Backstage", "CH 3"))
        self.label_Ch3_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch4.setText(_translate("widget_Calibration_Backstage", "CH 4"))
        self.label_Ch4_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch5.setText(_translate("widget_Calibration_Backstage", "CH 5"))
        self.label_Ch5_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch6.setText(_translate("widget_Calibration_Backstage", "CH 6"))
        self.label_Ch6_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch7.setText(_translate("widget_Calibration_Backstage", "CH 7"))
        self.label_Ch7_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch8.setText(_translate("widget_Calibration_Backstage", "CH 8"))
        self.label_Ch8_Result.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_Ch_Id.setText(_translate("widget_Calibration_Backstage", "  通道 ID"))
        self.label_Init.setText(_translate("widget_Calibration_Backstage", "初始采样值"))
        self.label_CaliA.setText(_translate("widget_Calibration_Backstage", "A 点校准"))
        self.label_CaliB.setText(_translate("widget_Calibration_Backstage", "B 点校准"))
        self.label_Bench1.setText(_translate("widget_Calibration_Backstage", "基准1检测"))
        self.label_Bench2.setText(_translate("widget_Calibration_Backstage", "基准2检测"))
        self.label_Bench3.setText(_translate("widget_Calibration_Backstage", "基准3检测"))
        self.label_Error.setText(_translate("widget_Calibration_Backstage", "平均误差"))
        self.label_Result.setText(_translate("widget_Calibration_Backstage", "校准结果"))
        self.label_Unit_Show.setText(_translate("widget_Calibration_Backstage", "单位"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Calibration_Backstage = QtWidgets.QWidget()
    ui = Ui_widget_Calibration_Backstage()
    ui.setupUi(widget_Calibration_Backstage)
    widget_Calibration_Backstage.show()
    sys.exit(app.exec_())

