# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_download.ui'
#
# Created: Fri Jul  7 18:50:32 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Download(object):
    def setupUi(self, widget_Download):
        widget_Download.setObjectName("widget_Download")
        widget_Download.resize(827, 0)
        self.textBrowser_Downloading_Info = QtWidgets.QTextBrowser(widget_Download)
        self.textBrowser_Downloading_Info.setGeometry(QtCore.QRect(472, 16, 351, 393))
        self.textBrowser_Downloading_Info.setObjectName("textBrowser_Downloading_Info")
        self.splitter_6 = QtWidgets.QSplitter(widget_Download)
        self.splitter_6.setGeometry(QtCore.QRect(88, 136, 377, 33))
        self.splitter_6.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_6.setObjectName("splitter_6")
        self.splitter_7 = QtWidgets.QSplitter(self.splitter_6)
        self.splitter_7.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_7.setObjectName("splitter_7")
        self.pushButton_Start_Download_5 = QtWidgets.QPushButton(self.splitter_7)
        self.pushButton_Start_Download_5.setObjectName("pushButton_Start_Download_5")
        self.pushButton_Stop_Download_3 = QtWidgets.QPushButton(self.splitter_7)
        self.pushButton_Stop_Download_3.setObjectName("pushButton_Stop_Download_3")
        self.label_Download_Flag = QtWidgets.QLabel(widget_Download)
        self.label_Download_Flag.setGeometry(QtCore.QRect(128, 352, 164, 40))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(30)
        font.setBold(True)
        font.setItalic(False)
        font.setUnderline(False)
        font.setWeight(75)
        font.setStyleStrategy(QtGui.QFont.PreferDefault)
        self.label_Download_Flag.setFont(font)
        self.label_Download_Flag.setAlignment(QtCore.Qt.AlignCenter)
        self.label_Download_Flag.setObjectName("label_Download_Flag")
        self.layoutWidget = QtWidgets.QWidget(widget_Download)
        self.layoutWidget.setGeometry(QtCore.QRect(8, 8, 457, 113))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_30 = QtWidgets.QLabel(self.layoutWidget)
        self.label_30.setObjectName("label_30")
        self.gridLayout.addWidget(self.label_30, 0, 0, 1, 1)
        self.lineEdit_Biospath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Biospath.setObjectName("lineEdit_Biospath")
        self.gridLayout.addWidget(self.lineEdit_Biospath, 0, 1, 1, 1)
        self.toolButton_Biospath = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_Biospath.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_Biospath.setObjectName("toolButton_Biospath")
        self.gridLayout.addWidget(self.toolButton_Biospath, 0, 2, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget)
        self.label_29.setObjectName("label_29")
        self.gridLayout.addWidget(self.label_29, 1, 0, 1, 1)
        self.lineEdit_Framepath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Framepath.setObjectName("lineEdit_Framepath")
        self.gridLayout.addWidget(self.lineEdit_Framepath, 1, 1, 1, 1)
        self.toolButton_Framepath = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_Framepath.setObjectName("toolButton_Framepath")
        self.gridLayout.addWidget(self.toolButton_Framepath, 1, 2, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget)
        self.label_28.setObjectName("label_28")
        self.gridLayout.addWidget(self.label_28, 2, 0, 1, 1)
        self.lineEdit_Ladderpath = QtWidgets.QLineEdit(self.layoutWidget)
        self.lineEdit_Ladderpath.setObjectName("lineEdit_Ladderpath")
        self.gridLayout.addWidget(self.lineEdit_Ladderpath, 2, 1, 1, 1)
        self.toolButton_Ladderpath = QtWidgets.QToolButton(self.layoutWidget)
        self.toolButton_Ladderpath.setObjectName("toolButton_Ladderpath")
        self.gridLayout.addWidget(self.toolButton_Ladderpath, 2, 2, 1, 1)
        self.label_6 = QtWidgets.QLabel(widget_Download)
        self.label_6.setGeometry(QtCore.QRect(96, 295, 54, 16))
        self.label_6.setObjectName("label_6")
        self.label_5 = QtWidgets.QLabel(widget_Download)
        self.label_5.setGeometry(QtCore.QRect(96, 268, 54, 16))
        self.label_5.setObjectName("label_5")
        self.label_4 = QtWidgets.QLabel(widget_Download)
        self.label_4.setGeometry(QtCore.QRect(96, 242, 54, 16))
        self.label_4.setObjectName("label_4")
        self.label_7 = QtWidgets.QLabel(widget_Download)
        self.label_7.setGeometry(QtCore.QRect(96, 321, 54, 16))
        self.label_7.setObjectName("label_7")
        self.label_23 = QtWidgets.QLabel(widget_Download)
        self.label_23.setGeometry(QtCore.QRect(9, 216, 48, 16))
        self.label_23.setObjectName("label_23")
        self.label_22 = QtWidgets.QLabel(widget_Download)
        self.label_22.setGeometry(QtCore.QRect(9, 190, 48, 16))
        self.label_22.setObjectName("label_22")
        self.label_24 = QtWidgets.QLabel(widget_Download)
        self.label_24.setGeometry(QtCore.QRect(9, 268, 36, 16))
        self.label_24.setObjectName("label_24")
        self.label_25 = QtWidgets.QLabel(widget_Download)
        self.label_25.setGeometry(QtCore.QRect(9, 321, 72, 16))
        self.label_25.setObjectName("label_25")
        self.label_26 = QtWidgets.QLabel(widget_Download)
        self.label_26.setGeometry(QtCore.QRect(9, 295, 48, 16))
        self.label_26.setObjectName("label_26")
        self.label_27 = QtWidgets.QLabel(widget_Download)
        self.label_27.setGeometry(QtCore.QRect(9, 242, 48, 16))
        self.label_27.setObjectName("label_27")
        self.label_2 = QtWidgets.QLabel(widget_Download)
        self.label_2.setGeometry(QtCore.QRect(96, 190, 54, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(widget_Download)
        self.label_3.setGeometry(QtCore.QRect(96, 216, 54, 16))
        self.label_3.setObjectName("label_3")

        self.retranslateUi(widget_Download)
        QtCore.QMetaObject.connectSlotsByName(widget_Download)

    def retranslateUi(self, widget_Download):
        _translate = QtCore.QCoreApplication.translate
        widget_Download.setWindowTitle(_translate("widget_Download", "Form"))
        self.pushButton_Start_Download_5.setText(_translate("widget_Download", "开始下载"))
        self.pushButton_Stop_Download_3.setText(_translate("widget_Download", "停止"))
        self.label_Download_Flag.setText(_translate("widget_Download", "下载状态"))
        self.label_30.setText(_translate("widget_Download", "BIOS"))
        self.lineEdit_Biospath.setText(_translate("widget_Download", "Bios Path"))
        self.toolButton_Biospath.setText(_translate("widget_Download", "..."))
        self.label_29.setText(_translate("widget_Download", "固件"))
        self.toolButton_Framepath.setText(_translate("widget_Download", "..."))
        self.label_28.setText(_translate("widget_Download", "梯形图"))
        self.toolButton_Ladderpath.setText(_translate("widget_Download", "..."))
        self.label_6.setText(_translate("widget_Download", "TextLabel"))
        self.label_5.setText(_translate("widget_Download", "TextLabel"))
        self.label_4.setText(_translate("widget_Download", "TextLabel"))
        self.label_7.setText(_translate("widget_Download", "TextLabel"))
        self.label_23.setText(_translate("widget_Download", "生产批次"))
        self.label_22.setText(_translate("widget_Download", "硬件版本"))
        self.label_24.setText(_translate("widget_Download", "序列号"))
        self.label_25.setText(_translate("widget_Download", "单次下载时间"))
        self.label_26.setText(_translate("widget_Download", "下载次数"))
        self.label_27.setText(_translate("widget_Download", "其他标识"))
        self.label_2.setText(_translate("widget_Download", "TextLabel"))
        self.label_3.setText(_translate("widget_Download", "TextLabel"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Download = QtWidgets.QWidget()
    ui = Ui_widget_Download()
    ui.setupUi(widget_Download)
    widget_Download.show()
    sys.exit(app.exec_())

