# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'hello_world.ui'
#
# Created: Fri Mar 17 18:54:02 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_mainlog(object):
    def setupUi(self, mainlog):
        mainlog.setObjectName("mainlog")
        mainlog.resize(877, 600)
        font = QtGui.QFont()
        font.setFamily("宋体")
        mainlog.setFont(font)
        mainlog.setLayoutDirection(QtCore.Qt.RightToLeft)
        mainlog.setAutoFillBackground(False)
        self.Click_me = QtWidgets.QPushButton(mainlog)
        self.Click_me.setGeometry(QtCore.QRect(773, 544, 75, 23))
        self.Click_me.setObjectName("Click_me")
        self.label = QtWidgets.QLabel(mainlog)
        self.label.setGeometry(QtCore.QRect(296, 8, 321, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(2)
        self.label.setMidLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(mainlog)
        self.label_2.setGeometry(QtCore.QRect(562, 544, 101, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.pushButton = QtWidgets.QPushButton(mainlog)
        self.pushButton.setGeometry(QtCore.QRect(672, 544, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_3 = QtWidgets.QLabel(mainlog)
        self.label_3.setGeometry(QtCore.QRect(48, 80, 92, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(mainlog)
        self.label_4.setGeometry(QtCore.QRect(536, 80, 45, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(mainlog)
        self.label_5.setGeometry(QtCore.QRect(664, 80, 45, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_5.setObjectName("label_5")
        self.label_6 = QtWidgets.QLabel(mainlog)
        self.label_6.setGeometry(QtCore.QRect(30, 48, 101, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.tableWidget = QtWidgets.QTableWidget(mainlog)
        self.tableWidget.setEnabled(False)
        self.tableWidget.setGeometry(QtCore.QRect(96, 248, 585, 192))
        self.tableWidget.setObjectName("tableWidget")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget.setHorizontalHeaderItem(8, item)
        self.tableWidget_2 = QtWidgets.QTableWidget(mainlog)
        self.tableWidget_2.setGeometry(QtCore.QRect(48, 136, 801, 385))
        self.tableWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 170, 255))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.label_7 = QtWidgets.QLabel(mainlog)
        self.label_7.setGeometry(QtCore.QRect(32, 112, 101, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")

        self.retranslateUi(mainlog)
        self.Click_me.clicked.connect(mainlog.close)
        QtCore.QMetaObject.connectSlotsByName(mainlog)
        mainlog.setTabOrder(self.tableWidget_2, self.tableWidget)
        mainlog.setTabOrder(self.tableWidget, self.pushButton)
        mainlog.setTabOrder(self.pushButton, self.Click_me)

    def retranslateUi(self, mainlog):
        _translate = QtCore.QCoreApplication.translate
        mainlog.setWindowTitle(_translate("mainlog", "mainlog"))
        self.Click_me.setText(_translate("mainlog", "退出"))
        self.label.setText(_translate("mainlog", "USBCANII2CANOpen Conversion Tool"))
        self.label_2.setText(_translate("mainlog", "载入数据文件:"))
        self.pushButton.setText(_translate("mainlog", "打开..."))
        self.label_3.setText(_translate("mainlog", "CAN1波特率："))
        self.label_4.setText(_translate("mainlog", "日期："))
        self.label_5.setText(_translate("mainlog", "时间："))
        self.label_6.setText(_translate("mainlog", "设置信息"))
        item = self.tableWidget.horizontalHeaderItem(0)
        item.setText(_translate("mainlog", "序列ID"))
        item = self.tableWidget.horizontalHeaderItem(1)
        item.setText(_translate("mainlog", "通道号"))
        item = self.tableWidget.horizontalHeaderItem(2)
        item.setText(_translate("mainlog", "时间标识"))
        item = self.tableWidget.horizontalHeaderItem(3)
        item.setText(_translate("mainlog", "新建列"))
        item = self.tableWidget.horizontalHeaderItem(4)
        item.setText(_translate("mainlog", "传输方向"))
        item = self.tableWidget.horizontalHeaderItem(5)
        item.setText(_translate("mainlog", "帧ID"))
        item = self.tableWidget.horizontalHeaderItem(6)
        item.setText(_translate("mainlog", "帧类型"))
        item = self.tableWidget.horizontalHeaderItem(7)
        item.setText(_translate("mainlog", "帧格式"))
        item = self.tableWidget.horizontalHeaderItem(8)
        item.setText(_translate("mainlog", "数据"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("mainlog", "序列ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("mainlog", "方向"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("mainlog", "描述"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("mainlog", "节点状态"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("mainlog", "COB-ID"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("mainlog", "节点ID"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("mainlog", "子索引"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("mainlog", "主索引"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("mainlog", "数据"))
        self.label_7.setText(_translate("mainlog", "帧解析"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    mainlog = QtWidgets.QDialog()
    ui = Ui_mainlog()
    ui.setupUi(mainlog)
    mainlog.show()
    sys.exit(app.exec_())

