# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'C:\Users\fan\Desktop\can_open_anal_copy.ui'
#
# Created: Sat Mar 18 17:42:54 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_usb2CanDataAnalTool(object):
    def setupUi(self, usb2CanDataAnalTool):
        usb2CanDataAnalTool.setObjectName("usb2CanDataAnalTool")
        usb2CanDataAnalTool.resize(877, 600)
        font = QtGui.QFont()
        font.setFamily("宋体")
        usb2CanDataAnalTool.setFont(font)
        usb2CanDataAnalTool.setLayoutDirection(QtCore.Qt.RightToLeft)
        usb2CanDataAnalTool.setAutoFillBackground(False)
        self.Click_me = QtWidgets.QPushButton(usb2CanDataAnalTool)
        self.Click_me.setGeometry(QtCore.QRect(773, 544, 75, 23))
        self.Click_me.setObjectName("Click_me")
        self.label = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.label.setGeometry(QtCore.QRect(296, 8, 321, 31))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(13)
        font.setBold(True)
        font.setWeight(75)
        self.label.setFont(font)
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setLineWidth(2)
        self.label.setMidLineWidth(1)
        self.label.setTextFormat(QtCore.Qt.AutoText)
        self.label.setOpenExternalLinks(False)
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(usb2CanDataAnalTool)
        self.pushButton.setGeometry(QtCore.QRect(48, 544, 75, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.label_2.setGeometry(QtCore.QRect(53, 80, 92, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.label_3.setGeometry(QtCore.QRect(520, 80, 45, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_3.setFont(font)
        self.label_3.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.label_3.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.label_4.setGeometry(QtCore.QRect(680, 80, 45, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_4.setFont(font)
        self.label_4.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.label_5.setGeometry(QtCore.QRect(30, 48, 101, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.tableWidget_2 = QtWidgets.QTableWidget(usb2CanDataAnalTool)
        self.tableWidget_2.setGeometry(QtCore.QRect(48, 136, 801, 385))
        self.tableWidget_2.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.tableWidget_2.setObjectName("tableWidget_2")
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setVerticalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        item.setBackground(QtGui.QColor(0, 170, 255))
        self.tableWidget_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(1, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(2, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(3, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(4, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(5, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(6, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(7, item)
        item = QtWidgets.QTableWidgetItem()
        self.tableWidget_2.setHorizontalHeaderItem(8, item)
        self.label_7 = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.label_7.setGeometry(QtCore.QRect(32, 112, 101, 16))
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(11)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.labelBaudrateSet = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.labelBaudrateSet.setGeometry(QtCore.QRect(144, 80, 145, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelBaudrateSet.setFont(font)
        self.labelBaudrateSet.setObjectName("labelBaudrateSet")
        self.labelTimeSet = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.labelTimeSet.setGeometry(QtCore.QRect(728, 80, 73, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelTimeSet.setFont(font)
        self.labelTimeSet.setObjectName("labelTimeSet")
        self.labelDateSet = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.labelDateSet.setGeometry(QtCore.QRect(568, 80, 97, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelDateSet.setFont(font)
        self.labelDateSet.setObjectName("labelDateSet")
        self.labelFileNameset = QtWidgets.QLabel(usb2CanDataAnalTool)
        self.labelFileNameset.setGeometry(QtCore.QRect(160, 552, 97, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.labelFileNameset.setFont(font)
        self.labelFileNameset.setObjectName("labelFileNameset")

        self.retranslateUi(usb2CanDataAnalTool)
        self.Click_me.clicked.connect(usb2CanDataAnalTool.close)
        QtCore.QMetaObject.connectSlotsByName(usb2CanDataAnalTool)
        usb2CanDataAnalTool.setTabOrder(self.tableWidget_2, self.pushButton)
        usb2CanDataAnalTool.setTabOrder(self.pushButton, self.Click_me)

    def retranslateUi(self, usb2CanDataAnalTool):
        _translate = QtCore.QCoreApplication.translate
        usb2CanDataAnalTool.setWindowTitle(_translate("usb2CanDataAnalTool", "mainlog"))
        self.Click_me.setText(_translate("usb2CanDataAnalTool", "退出"))
        self.label.setText(_translate("usb2CanDataAnalTool", "USBCANII2CANOpen Conversion Tool"))
        self.pushButton.setText(_translate("usb2CanDataAnalTool", "打开..."))
        self.label_2.setText(_translate("usb2CanDataAnalTool", "CAN1波特率："))
        self.label_3.setText(_translate("usb2CanDataAnalTool", "日期："))
        self.label_4.setText(_translate("usb2CanDataAnalTool", "时间："))
        self.label_5.setText(_translate("usb2CanDataAnalTool", "设置信息"))
        item = self.tableWidget_2.verticalHeaderItem(0)
        item.setText(_translate("usb2CanDataAnalTool", "Data"))
        item = self.tableWidget_2.horizontalHeaderItem(0)
        item.setText(_translate("usb2CanDataAnalTool", "序列ID"))
        item = self.tableWidget_2.horizontalHeaderItem(1)
        item.setText(_translate("usb2CanDataAnalTool", "方向"))
        item = self.tableWidget_2.horizontalHeaderItem(2)
        item.setText(_translate("usb2CanDataAnalTool", "描述"))
        item = self.tableWidget_2.horizontalHeaderItem(3)
        item.setText(_translate("usb2CanDataAnalTool", "节点状态"))
        item = self.tableWidget_2.horizontalHeaderItem(4)
        item.setText(_translate("usb2CanDataAnalTool", "COB-ID"))
        item = self.tableWidget_2.horizontalHeaderItem(5)
        item.setText(_translate("usb2CanDataAnalTool", "节点ID"))
        item = self.tableWidget_2.horizontalHeaderItem(6)
        item.setText(_translate("usb2CanDataAnalTool", "子索引"))
        item = self.tableWidget_2.horizontalHeaderItem(7)
        item.setText(_translate("usb2CanDataAnalTool", "主索引"))
        item = self.tableWidget_2.horizontalHeaderItem(8)
        item.setText(_translate("usb2CanDataAnalTool", "数据"))
        self.label_7.setText(_translate("usb2CanDataAnalTool", "帧解析"))
        self.labelBaudrateSet.setText(_translate("usb2CanDataAnalTool", "0"))
        self.labelTimeSet.setText(_translate("usb2CanDataAnalTool", "0"))
        self.labelDateSet.setText(_translate("usb2CanDataAnalTool", "0"))
        self.labelFileNameset.setText(_translate("usb2CanDataAnalTool", "当前：无数据"))

