# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redmine_count_panel.ui'
#
# Created: Tue Sep 25 01:43:13 2018
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RedminePanel(object):
    def setupUi(self, RedminePanel):
        RedminePanel.setObjectName("RedminePanel")
        RedminePanel.resize(1065, 780)
        self.verticalLayout = QtWidgets.QVBoxLayout(RedminePanel)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.checkBox_statusCheck = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_statusCheck.setObjectName("checkBox_statusCheck")
        self.gridLayout_2.addWidget(self.checkBox_statusCheck, 3, 1, 1, 1)
        self.pushButton_assignedAdd = QtWidgets.QPushButton(RedminePanel)
        self.pushButton_assignedAdd.setObjectName("pushButton_assignedAdd")
        self.gridLayout_2.addWidget(self.pushButton_assignedAdd, 1, 3, 1, 1)
        self.comboBox_assignedTo = QtWidgets.QComboBox(RedminePanel)
        self.comboBox_assignedTo.setObjectName("comboBox_assignedTo")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.gridLayout_2.addWidget(self.comboBox_assignedTo, 1, 2, 1, 1)
        self.checkBox_statusOver = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_statusOver.setObjectName("checkBox_statusOver")
        self.gridLayout_2.addWidget(self.checkBox_statusOver, 5, 1, 1, 1)
        self.pushButton_renew = QtWidgets.QPushButton(RedminePanel)
        self.pushButton_renew.setObjectName("pushButton_renew")
        self.gridLayout_2.addWidget(self.pushButton_renew, 3, 6, 1, 1)
        self.checkBox_statusWaitcheck = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_statusWaitcheck.setObjectName("checkBox_statusWaitcheck")
        self.gridLayout_2.addWidget(self.checkBox_statusWaitcheck, 4, 1, 1, 1)
        self.pushButton_assignedDel = QtWidgets.QPushButton(RedminePanel)
        self.pushButton_assignedDel.setObjectName("pushButton_assignedDel")
        self.gridLayout_2.addWidget(self.pushButton_assignedDel, 1, 4, 1, 1)
        self.listWidget_partMembers = QtWidgets.QListWidget(RedminePanel)
        self.listWidget_partMembers.setObjectName("listWidget_partMembers")
        self.gridLayout_2.addWidget(self.listWidget_partMembers, 2, 2, 4, 2)
        self.listWidget_assignedTo = QtWidgets.QListWidget(RedminePanel)
        self.listWidget_assignedTo.setObjectName("listWidget_assignedTo")
        self.gridLayout_2.addWidget(self.listWidget_assignedTo, 2, 4, 4, 2)
        self.pushButton_set = QtWidgets.QPushButton(RedminePanel)
        self.pushButton_set.setObjectName("pushButton_set")
        self.gridLayout_2.addWidget(self.pushButton_set, 2, 6, 1, 1)
        self.pushButton_count = QtWidgets.QPushButton(RedminePanel)
        self.pushButton_count.setObjectName("pushButton_count")
        self.gridLayout_2.addWidget(self.pushButton_count, 4, 6, 1, 1)
        self.pushButton_assignedClear = QtWidgets.QPushButton(RedminePanel)
        self.pushButton_assignedClear.setObjectName("pushButton_assignedClear")
        self.gridLayout_2.addWidget(self.pushButton_assignedClear, 1, 5, 1, 1)
        self.groupBox = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox.setObjectName("groupBox")
        self.gridLayout_2.addWidget(self.groupBox, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_2.setObjectName("groupBox_2")
        self.gridLayout_2.addWidget(self.groupBox_2, 0, 1, 1, 1)
        self.checkBox_statusNew = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_statusNew.setObjectName("checkBox_statusNew")
        self.gridLayout_2.addWidget(self.checkBox_statusNew, 1, 1, 1, 1)
        self.checkBox_taskTest = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_taskTest.setObjectName("checkBox_taskTest")
        self.gridLayout_2.addWidget(self.checkBox_taskTest, 1, 0, 1, 1)
        self.checkBox_taskHard = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_taskHard.setObjectName("checkBox_taskHard")
        self.gridLayout_2.addWidget(self.checkBox_taskHard, 4, 0, 1, 1)
        self.checkBox_taskBug = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_taskBug.setObjectName("checkBox_taskBug")
        self.gridLayout_2.addWidget(self.checkBox_taskBug, 2, 0, 1, 1)
        self.checkBox_taskTask = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_taskTask.setObjectName("checkBox_taskTask")
        self.gridLayout_2.addWidget(self.checkBox_taskTask, 3, 0, 1, 1)
        self.checkBox_statusWorking = QtWidgets.QCheckBox(RedminePanel)
        self.checkBox_statusWorking.setObjectName("checkBox_statusWorking")
        self.gridLayout_2.addWidget(self.checkBox_statusWorking, 2, 1, 1, 1)
        self.tableWidget_taskList = QtWidgets.QTableWidget(RedminePanel)
        self.tableWidget_taskList.setObjectName("tableWidget_taskList")
        self.gridLayout_2.addWidget(self.tableWidget_taskList, 7, 0, 1, 7)
        self.groupBox_3 = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_3.setObjectName("groupBox_3")
        self.gridLayout_2.addWidget(self.groupBox_3, 0, 2, 1, 4)
        self.groupBox_4 = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_4.setObjectName("groupBox_4")
        self.gridLayout_2.addWidget(self.groupBox_4, 0, 6, 1, 1)
        self.groupBox_5 = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_5.setObjectName("groupBox_5")
        self.gridLayout_2.addWidget(self.groupBox_5, 6, 0, 1, 7)
        self.verticalLayout.addLayout(self.gridLayout_2)

        self.retranslateUi(RedminePanel)
        QtCore.QMetaObject.connectSlotsByName(RedminePanel)

    def retranslateUi(self, RedminePanel):
        _translate = QtCore.QCoreApplication.translate
        RedminePanel.setWindowTitle(_translate("RedminePanel", "Dialog"))
        self.checkBox_statusCheck.setText(_translate("RedminePanel", "评审或审核"))
        self.pushButton_assignedAdd.setText(_translate("RedminePanel", "添加"))
        self.comboBox_assignedTo.setItemText(0, _translate("RedminePanel", "软件一部"))
        self.comboBox_assignedTo.setItemText(1, _translate("RedminePanel", "软件二部"))
        self.comboBox_assignedTo.setItemText(2, _translate("RedminePanel", "软件三部"))
        self.comboBox_assignedTo.setItemText(3, _translate("RedminePanel", "测试部"))
        self.comboBox_assignedTo.setItemText(4, _translate("RedminePanel", "技术支持部"))
        self.comboBox_assignedTo.setItemText(5, _translate("RedminePanel", "外贸支持"))
        self.comboBox_assignedTo.setItemText(6, _translate("RedminePanel", "全部"))
        self.checkBox_statusOver.setText(_translate("RedminePanel", "已完成"))
        self.pushButton_renew.setText(_translate("RedminePanel", "更新数据库"))
        self.checkBox_statusWaitcheck.setText(_translate("RedminePanel", "待验证"))
        self.pushButton_assignedDel.setText(_translate("RedminePanel", "删除选中"))
        self.pushButton_set.setText(_translate("RedminePanel", "查询设置"))
        self.pushButton_count.setText(_translate("RedminePanel", "查询"))
        self.pushButton_assignedClear.setText(_translate("RedminePanel", "清除"))
        self.groupBox.setTitle(_translate("RedminePanel", "任务类型"))
        self.groupBox_2.setTitle(_translate("RedminePanel", "任务状态"))
        self.checkBox_statusNew.setText(_translate("RedminePanel", "新建"))
        self.checkBox_taskTest.setText(_translate("RedminePanel", "测试"))
        self.checkBox_taskHard.setText(_translate("RedminePanel", "硬件任务"))
        self.checkBox_taskBug.setText(_translate("RedminePanel", "BUG"))
        self.checkBox_taskTask.setText(_translate("RedminePanel", "任务"))
        self.checkBox_statusWorking.setText(_translate("RedminePanel", "进行中"))
        self.groupBox_3.setTitle(_translate("RedminePanel", "指派给"))
        self.groupBox_4.setTitle(_translate("RedminePanel", "查询"))
        self.groupBox_5.setTitle(_translate("RedminePanel", "任务清单"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RedminePanel = QtWidgets.QDialog()
    ui = Ui_RedminePanel()
    ui.setupUi(RedminePanel)
    RedminePanel.show()
    sys.exit(app.exec_())

