# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'redmine_count_panel.ui'
#
# Created: Thu Sep  6 22:03:39 2018
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_RedminePanel(object):
    def setupUi(self, RedminePanel):
        RedminePanel.setObjectName("RedminePanel")
        RedminePanel.resize(700, 478)
        self.groupBox_taskType = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_taskType.setGeometry(QtCore.QRect(10, 10, 171, 151))
        self.groupBox_taskType.setObjectName("groupBox_taskType")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox_taskType)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 151, 121))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.checkBox_taskTest = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_taskTest.setObjectName("checkBox_taskTest")
        self.verticalLayout.addWidget(self.checkBox_taskTest)
        self.checkBox_taskBug = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_taskBug.setObjectName("checkBox_taskBug")
        self.verticalLayout.addWidget(self.checkBox_taskBug)
        self.checkBox_taskHard = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_taskHard.setObjectName("checkBox_taskHard")
        self.verticalLayout.addWidget(self.checkBox_taskHard)
        self.checkBox_taskTask = QtWidgets.QCheckBox(self.layoutWidget)
        self.checkBox_taskTask.setObjectName("checkBox_taskTask")
        self.verticalLayout.addWidget(self.checkBox_taskTask)
        self.groupBox_taskStatus = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_taskStatus.setGeometry(QtCore.QRect(189, 10, 181, 151))
        self.groupBox_taskStatus.setObjectName("groupBox_taskStatus")
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox_taskStatus)
        self.layoutWidget1.setGeometry(QtCore.QRect(10, 20, 161, 121))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget1)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.checkBox_statusNew = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_statusNew.setObjectName("checkBox_statusNew")
        self.verticalLayout_2.addWidget(self.checkBox_statusNew)
        self.checkBox_statusWorking = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_statusWorking.setObjectName("checkBox_statusWorking")
        self.verticalLayout_2.addWidget(self.checkBox_statusWorking)
        self.checkBox_statusCheck = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_statusCheck.setObjectName("checkBox_statusCheck")
        self.verticalLayout_2.addWidget(self.checkBox_statusCheck)
        self.checkBox_statusWaitcheck = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_statusWaitcheck.setObjectName("checkBox_statusWaitcheck")
        self.verticalLayout_2.addWidget(self.checkBox_statusWaitcheck)
        self.checkBox_statusOver = QtWidgets.QCheckBox(self.layoutWidget1)
        self.checkBox_statusOver.setObjectName("checkBox_statusOver")
        self.verticalLayout_2.addWidget(self.checkBox_statusOver)
        self.groupBox_assigned = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_assigned.setGeometry(QtCore.QRect(380, 10, 311, 151))
        self.groupBox_assigned.setObjectName("groupBox_assigned")
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox_assigned)
        self.layoutWidget2.setGeometry(QtCore.QRect(10, 20, 291, 121))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget2)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.pushButton_assignedClear = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_assignedClear.setObjectName("pushButton_assignedClear")
        self.gridLayout.addWidget(self.pushButton_assignedClear, 0, 2, 1, 1)
        self.comboBox_assignedTo = QtWidgets.QComboBox(self.layoutWidget2)
        self.comboBox_assignedTo.setObjectName("comboBox_assignedTo")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.comboBox_assignedTo.addItem("")
        self.gridLayout.addWidget(self.comboBox_assignedTo, 0, 0, 1, 1)
        self.pushButton_assignedAdd = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_assignedAdd.setObjectName("pushButton_assignedAdd")
        self.gridLayout.addWidget(self.pushButton_assignedAdd, 0, 1, 1, 1)
        self.listWidget_partMembers = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_partMembers.setObjectName("listWidget_partMembers")
        item = QtWidgets.QListWidgetItem()
        self.listWidget_partMembers.addItem(item)
        self.gridLayout.addWidget(self.listWidget_partMembers, 1, 0, 1, 1)
        self.listWidget_assignedTo = QtWidgets.QListWidget(self.layoutWidget2)
        self.listWidget_assignedTo.setObjectName("listWidget_assignedTo")
        self.gridLayout.addWidget(self.listWidget_assignedTo, 1, 1, 1, 2)
        self.groupBox_taskList = QtWidgets.QGroupBox(RedminePanel)
        self.groupBox_taskList.setGeometry(QtCore.QRect(10, 170, 681, 291))
        self.groupBox_taskList.setObjectName("groupBox_taskList")
        self.tableWidget_taskList = QtWidgets.QTableWidget(self.groupBox_taskList)
        self.tableWidget_taskList.setGeometry(QtCore.QRect(10, 20, 661, 51))
        self.tableWidget_taskList.setObjectName("tableWidget_taskList")

        self.retranslateUi(RedminePanel)
        QtCore.QMetaObject.connectSlotsByName(RedminePanel)

    def retranslateUi(self, RedminePanel):
        _translate = QtCore.QCoreApplication.translate
        RedminePanel.setWindowTitle(_translate("RedminePanel", "Dialog"))
        self.groupBox_taskType.setTitle(_translate("RedminePanel", "任务类型"))
        self.checkBox_taskTest.setText(_translate("RedminePanel", "测试"))
        self.checkBox_taskBug.setText(_translate("RedminePanel", "BUG"))
        self.checkBox_taskHard.setText(_translate("RedminePanel", "硬件任务"))
        self.checkBox_taskTask.setText(_translate("RedminePanel", "任务"))
        self.groupBox_taskStatus.setTitle(_translate("RedminePanel", "任务状态"))
        self.checkBox_statusNew.setText(_translate("RedminePanel", "新建"))
        self.checkBox_statusWorking.setText(_translate("RedminePanel", "进行中"))
        self.checkBox_statusCheck.setText(_translate("RedminePanel", "评审或审核"))
        self.checkBox_statusWaitcheck.setText(_translate("RedminePanel", "待验证"))
        self.checkBox_statusOver.setText(_translate("RedminePanel", "已完成"))
        self.groupBox_assigned.setTitle(_translate("RedminePanel", "指派给"))
        self.pushButton_assignedClear.setText(_translate("RedminePanel", "清除"))
        self.comboBox_assignedTo.setItemText(0, _translate("RedminePanel", "软件一部"))
        self.comboBox_assignedTo.setItemText(1, _translate("RedminePanel", "软件二部"))
        self.comboBox_assignedTo.setItemText(2, _translate("RedminePanel", "软件三部"))
        self.comboBox_assignedTo.setItemText(3, _translate("RedminePanel", "测试部"))
        self.comboBox_assignedTo.setItemText(4, _translate("RedminePanel", "技术支持部"))
        self.comboBox_assignedTo.setItemText(5, _translate("RedminePanel", "外贸支持"))
        self.comboBox_assignedTo.setItemText(6, _translate("RedminePanel", "全部"))
        self.pushButton_assignedAdd.setText(_translate("RedminePanel", "添加"))
        __sortingEnabled = self.listWidget_partMembers.isSortingEnabled()
        self.listWidget_partMembers.setSortingEnabled(False)
        item = self.listWidget_partMembers.item(0)
        item.setText(_translate("RedminePanel", "全部"))
        self.listWidget_partMembers.setSortingEnabled(__sortingEnabled)
        self.groupBox_taskList.setTitle(_translate("RedminePanel", "任务清单"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    RedminePanel = QtWidgets.QDialog()
    ui = Ui_RedminePanel()
    ui.setupUi(RedminePanel)
    RedminePanel.show()
    sys.exit(app.exec_())

