# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_calibration_backstage_copycopy.ui'
#
# Created: Mon May  8 01:30:57 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Calibration_Backstage(object):
    def setupUi(self, widget_Calibration_Backstage):
        widget_Calibration_Backstage.setObjectName("widget_Calibration_Backstage")
        widget_Calibration_Backstage.resize(842, 396)
        self.groupBox = QtWidgets.QGroupBox(widget_Calibration_Backstage)
        self.groupBox.setGeometry(QtCore.QRect(0, 8, 833, 377))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(8, 16, 681, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout.addWidget(self.label_4)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout.addWidget(self.label_5)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout.addWidget(self.label_6)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout.addWidget(self.label_7)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout.addWidget(self.label_8)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget)
        self.label_17.setObjectName("label_17")
        self.horizontalLayout.addWidget(self.label_17)
        self.layoutWidget1 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget1.setGeometry(QtCore.QRect(8, 288, 681, 33))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.layoutWidget1)
        self.horizontalLayout_10.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.label_16 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_16.setObjectName("label_16")
        self.horizontalLayout_10.addWidget(self.label_16)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.horizontalLayout_10.addWidget(self.lineEdit_14)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.horizontalLayout_10.addWidget(self.lineEdit_28)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.horizontalLayout_10.addWidget(self.lineEdit_29)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.horizontalLayout_10.addWidget(self.lineEdit_39)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.horizontalLayout_10.addWidget(self.lineEdit_44)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.horizontalLayout_10.addWidget(self.lineEdit_50)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.layoutWidget1)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.horizontalLayout_10.addWidget(self.lineEdit_56)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget1)
        self.label_26.setObjectName("label_26")
        self.horizontalLayout_10.addWidget(self.label_26)
        self.layoutWidget2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget2.setGeometry(QtCore.QRect(8, 160, 681, 30))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout(self.layoutWidget2)
        self.horizontalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_6.addWidget(self.label_11)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.horizontalLayout_6.addWidget(self.lineEdit_10)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.horizontalLayout_6.addWidget(self.lineEdit_21)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.horizontalLayout_6.addWidget(self.lineEdit_33)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.horizontalLayout_6.addWidget(self.lineEdit_20)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.horizontalLayout_6.addWidget(self.lineEdit_19)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.horizontalLayout_6.addWidget(self.lineEdit_18)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.horizontalLayout_6.addWidget(self.lineEdit_17)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.horizontalLayout_6.addWidget(self.label_22)
        self.layoutWidget3 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget3.setGeometry(QtCore.QRect(8, 88, 681, 33))
        self.layoutWidget3.setObjectName("layoutWidget3")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout(self.layoutWidget3)
        self.horizontalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_10 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_4.addWidget(self.label_10)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.horizontalLayout_4.addWidget(self.lineEdit_8)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.horizontalLayout_4.addWidget(self.lineEdit_15)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.horizontalLayout_4.addWidget(self.lineEdit_22)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.horizontalLayout_4.addWidget(self.lineEdit_23)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.horizontalLayout_4.addWidget(self.lineEdit_24)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.horizontalLayout_4.addWidget(self.lineEdit_45)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.layoutWidget3)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.horizontalLayout_4.addWidget(self.lineEdit_51)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget3)
        self.label_18.setObjectName("label_18")
        self.horizontalLayout_4.addWidget(self.label_18)
        self.layoutWidget4 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget4.setGeometry(QtCore.QRect(8, 224, 681, 30))
        self.layoutWidget4.setObjectName("layoutWidget4")
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout(self.layoutWidget4)
        self.horizontalLayout_8.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_14 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_14.setObjectName("label_14")
        self.horizontalLayout_8.addWidget(self.label_14)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.horizontalLayout_8.addWidget(self.lineEdit_12)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.horizontalLayout_8.addWidget(self.lineEdit_26)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.horizontalLayout_8.addWidget(self.lineEdit_31)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.horizontalLayout_8.addWidget(self.lineEdit_37)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.horizontalLayout_8.addWidget(self.lineEdit_42)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.horizontalLayout_8.addWidget(self.lineEdit_48)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.layoutWidget4)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.horizontalLayout_8.addWidget(self.lineEdit_54)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget4)
        self.label_24.setObjectName("label_24")
        self.horizontalLayout_8.addWidget(self.label_24)
        self.layoutWidget5 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget5.setGeometry(QtCore.QRect(8, 48, 681, 33))
        self.layoutWidget5.setObjectName("layoutWidget5")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget5)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_2.addWidget(self.label_9)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout_2.addWidget(self.lineEdit)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.horizontalLayout_2.addWidget(self.lineEdit_3)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.horizontalLayout_2.addWidget(self.lineEdit_4)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.horizontalLayout_2.addWidget(self.lineEdit_5)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.horizontalLayout_2.addWidget(self.lineEdit_6)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget5)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.horizontalLayout_2.addWidget(self.lineEdit_7)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget5)
        self.label_20.setObjectName("label_20")
        self.horizontalLayout_2.addWidget(self.label_20)
        self.layoutWidget6 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget6.setGeometry(QtCore.QRect(8, 128, 681, 30))
        self.layoutWidget6.setObjectName("layoutWidget6")
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout(self.layoutWidget6)
        self.horizontalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_12 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_12.setObjectName("label_12")
        self.horizontalLayout_5.addWidget(self.label_12)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.horizontalLayout_5.addWidget(self.lineEdit_9)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.horizontalLayout_5.addWidget(self.lineEdit_16)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.horizontalLayout_5.addWidget(self.lineEdit_34)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.horizontalLayout_5.addWidget(self.lineEdit_35)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.horizontalLayout_5.addWidget(self.lineEdit_40)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.horizontalLayout_5.addWidget(self.lineEdit_46)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.layoutWidget6)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.horizontalLayout_5.addWidget(self.lineEdit_52)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget6)
        self.label_21.setObjectName("label_21")
        self.horizontalLayout_5.addWidget(self.label_21)
        self.layoutWidget7 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget7.setGeometry(QtCore.QRect(8, 192, 681, 31))
        self.layoutWidget7.setObjectName("layoutWidget7")
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout(self.layoutWidget7)
        self.horizontalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_13 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_13.setObjectName("label_13")
        self.horizontalLayout_7.addWidget(self.label_13)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.horizontalLayout_7.addWidget(self.lineEdit_11)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.horizontalLayout_7.addWidget(self.lineEdit_27)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.horizontalLayout_7.addWidget(self.lineEdit_32)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.horizontalLayout_7.addWidget(self.lineEdit_36)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.horizontalLayout_7.addWidget(self.lineEdit_41)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.horizontalLayout_7.addWidget(self.lineEdit_47)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.layoutWidget7)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.horizontalLayout_7.addWidget(self.lineEdit_53)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget7)
        self.label_23.setObjectName("label_23")
        self.horizontalLayout_7.addWidget(self.label_23)
        self.layoutWidget8 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget8.setGeometry(QtCore.QRect(8, 256, 681, 30))
        self.layoutWidget8.setObjectName("layoutWidget8")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.layoutWidget8)
        self.horizontalLayout_9.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.label_15 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_15.setObjectName("label_15")
        self.horizontalLayout_9.addWidget(self.label_15)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.horizontalLayout_9.addWidget(self.lineEdit_13)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.horizontalLayout_9.addWidget(self.lineEdit_25)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.horizontalLayout_9.addWidget(self.lineEdit_30)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.horizontalLayout_9.addWidget(self.lineEdit_38)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.horizontalLayout_9.addWidget(self.lineEdit_43)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.horizontalLayout_9.addWidget(self.lineEdit_49)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.layoutWidget8)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.horizontalLayout_9.addWidget(self.lineEdit_55)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget8)
        self.label_25.setObjectName("label_25")
        self.horizontalLayout_9.addWidget(self.label_25)

        self.retranslateUi(widget_Calibration_Backstage)
        QtCore.QMetaObject.connectSlotsByName(widget_Calibration_Backstage)

    def retranslateUi(self, widget_Calibration_Backstage):
        _translate = QtCore.QCoreApplication.translate
        widget_Calibration_Backstage.setWindowTitle(_translate("widget_Calibration_Backstage", "Form"))
        self.label.setText(_translate("widget_Calibration_Backstage", "  通道 ID"))
        self.label_2.setText(_translate("widget_Calibration_Backstage", "当前采样"))
        self.label_3.setText(_translate("widget_Calibration_Backstage", "A 点校准"))
        self.label_4.setText(_translate("widget_Calibration_Backstage", "B 点校准"))
        self.label_5.setText(_translate("widget_Calibration_Backstage", "R68 检测(℃)"))
        self.label_6.setText(_translate("widget_Calibration_Backstage", "R150检测(℃)"))
        self.label_7.setText(_translate("widget_Calibration_Backstage", "R200检测(℃)"))
        self.label_8.setText(_translate("widget_Calibration_Backstage", "平均误差(℃)"))
        self.label_17.setText(_translate("widget_Calibration_Backstage", "校准结果"))
        self.label_16.setText(_translate("widget_Calibration_Backstage", "    CH 8    "))
        self.label_26.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_11.setText(_translate("widget_Calibration_Backstage", "    CH 4    "))
        self.label_22.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_10.setText(_translate("widget_Calibration_Backstage", "    CH 2    "))
        self.label_18.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_14.setText(_translate("widget_Calibration_Backstage", "    CH 6    "))
        self.label_24.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_9.setText(_translate("widget_Calibration_Backstage", "    CH 1    "))
        self.label_20.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_12.setText(_translate("widget_Calibration_Backstage", "    CH 3    "))
        self.label_21.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_13.setText(_translate("widget_Calibration_Backstage", "    CH 5    "))
        self.label_23.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_15.setText(_translate("widget_Calibration_Backstage", "    CH 7    "))
        self.label_25.setText(_translate("widget_Calibration_Backstage", "检测中..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Calibration_Backstage = QtWidgets.QWidget()
    ui = Ui_widget_Calibration_Backstage()
    ui.setupUi(widget_Calibration_Backstage)
    widget_Calibration_Backstage.show()
    sys.exit(app.exec_())

