# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_setting.ui'
#
# Created: Mon May  8 01:30:57 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Setting(object):
    def setupUi(self, widget_Setting):
        widget_Setting.setObjectName("widget_Setting")
        widget_Setting.resize(135, 513)
        self.groupBox_5 = QtWidgets.QGroupBox(widget_Setting)
        self.groupBox_5.setGeometry(QtCore.QRect(9, 416, 124, 105))
        self.groupBox_5.setObjectName("groupBox_5")
        self.layoutWidget_6 = QtWidgets.QWidget(self.groupBox_5)
        self.layoutWidget_6.setGeometry(QtCore.QRect(16, 24, 97, 65))
        self.layoutWidget_6.setObjectName("layoutWidget_6")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.layoutWidget_6)
        self.verticalLayout_6.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.pushButton_Open_Ports = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_Open_Ports.setObjectName("pushButton_Open_Ports")
        self.verticalLayout_6.addWidget(self.pushButton_Open_Ports)
        self.pushButton_Reset_Module = QtWidgets.QPushButton(self.layoutWidget_6)
        self.pushButton_Reset_Module.setObjectName("pushButton_Reset_Module")
        self.verticalLayout_6.addWidget(self.pushButton_Reset_Module)
        self.layoutWidget = QtWidgets.QWidget(widget_Setting)
        self.layoutWidget.setGeometry(QtCore.QRect(9, 0, 126, 393))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.groupBox_3 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox_3)
        self.layoutWidget_2.setGeometry(QtCore.QRect(16, 16, 97, 84))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_PortA_Id = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_PortA_Id.setStyleSheet("QPushButton{ color: red }")
        self.label_PortA_Id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PortA_Id.setObjectName("label_PortA_Id")
        self.verticalLayout_2.addWidget(self.label_PortA_Id)
        self.comboBox_PortA_Id = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_PortA_Id.setObjectName("comboBox_PortA_Id")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_PortA_Id)
        self.label_PortA_Paudrate = QtWidgets.QLabel(self.layoutWidget_2)
        self.label_PortA_Paudrate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PortA_Paudrate.setObjectName("label_PortA_Paudrate")
        self.verticalLayout_2.addWidget(self.label_PortA_Paudrate)
        self.comboBox_PortA_Paudrate = QtWidgets.QComboBox(self.layoutWidget_2)
        self.comboBox_PortA_Paudrate.setObjectName("comboBox_PortA_Paudrate")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.verticalLayout_2.addWidget(self.comboBox_PortA_Paudrate)
        self.gridLayout.addWidget(self.groupBox_3, 0, 0, 1, 1)
        self.groupBox_2 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(16, 16, 97, 84))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.layoutWidget_3)
        self.verticalLayout_4.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label_PortB_Id = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_PortB_Id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PortB_Id.setObjectName("label_PortB_Id")
        self.verticalLayout_4.addWidget(self.label_PortB_Id)
        self.comboBox_PortB_Id = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_PortB_Id.setObjectName("comboBox_PortB_Id")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_PortB_Id)
        self.label_PortB_Paudrate = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_PortB_Paudrate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PortB_Paudrate.setObjectName("label_PortB_Paudrate")
        self.verticalLayout_4.addWidget(self.label_PortB_Paudrate)
        self.comboBox_PortB_Paudrate = QtWidgets.QComboBox(self.layoutWidget_3)
        self.comboBox_PortB_Paudrate.setObjectName("comboBox_PortB_Paudrate")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.verticalLayout_4.addWidget(self.comboBox_PortB_Paudrate)
        self.gridLayout.addWidget(self.groupBox_2, 1, 0, 1, 1)
        self.groupBox_4 = QtWidgets.QGroupBox(self.layoutWidget)
        self.groupBox_4.setObjectName("groupBox_4")
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_4)
        self.layoutWidget_4.setGeometry(QtCore.QRect(16, 16, 97, 84))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.layoutWidget_4)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label_PortC_Id = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_PortC_Id.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PortC_Id.setObjectName("label_PortC_Id")
        self.verticalLayout_5.addWidget(self.label_PortC_Id)
        self.comboBox_PortC_Id = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_PortC_Id.setObjectName("comboBox_PortC_Id")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.comboBox_PortC_Id.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_PortC_Id)
        self.label_PortC_Paudrate = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_PortC_Paudrate.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.label_PortC_Paudrate.setObjectName("label_PortC_Paudrate")
        self.verticalLayout_5.addWidget(self.label_PortC_Paudrate)
        self.comboBox_PortC_Paudrate = QtWidgets.QComboBox(self.layoutWidget_4)
        self.comboBox_PortC_Paudrate.setObjectName("comboBox_PortC_Paudrate")
        self.comboBox_PortC_Paudrate.addItem("")
        self.comboBox_PortC_Paudrate.addItem("")
        self.comboBox_PortC_Paudrate.addItem("")
        self.comboBox_PortC_Paudrate.addItem("")
        self.comboBox_PortC_Paudrate.addItem("")
        self.verticalLayout_5.addWidget(self.comboBox_PortC_Paudrate)
        self.gridLayout.addWidget(self.groupBox_4, 2, 0, 1, 1)

        self.retranslateUi(widget_Setting)
        QtCore.QMetaObject.connectSlotsByName(widget_Setting)

    def retranslateUi(self, widget_Setting):
        _translate = QtCore.QCoreApplication.translate
        widget_Setting.setWindowTitle(_translate("widget_Setting", "Form"))
        self.groupBox_5.setTitle(_translate("widget_Setting", "设置完毕"))
        self.pushButton_Open_Ports.setText(_translate("widget_Setting", "打开串口"))
        self.pushButton_Reset_Module.setText(_translate("widget_Setting", "复位被测板"))
        self.groupBox_3.setTitle(_translate("widget_Setting", "Port A 连接被测板"))
        self.label_PortA_Id.setText(_translate("widget_Setting", "串口"))
        self.comboBox_PortA_Id.setItemText(0, _translate("widget_Setting", "COM1"))
        self.comboBox_PortA_Id.setItemText(1, _translate("widget_Setting", "COM2"))
        self.comboBox_PortA_Id.setItemText(2, _translate("widget_Setting", "COM3"))
        self.comboBox_PortA_Id.setItemText(3, _translate("widget_Setting", "COM4"))
        self.comboBox_PortA_Id.setItemText(4, _translate("widget_Setting", "COM5"))
        self.comboBox_PortA_Id.setItemText(5, _translate("widget_Setting", "COM6"))
        self.comboBox_PortA_Id.setItemText(6, _translate("widget_Setting", "COM7"))
        self.comboBox_PortA_Id.setItemText(7, _translate("widget_Setting", "COM8"))
        self.comboBox_PortA_Id.setItemText(8, _translate("widget_Setting", "COM9"))
        self.comboBox_PortA_Id.setItemText(9, _translate("widget_Setting", "COM10"))
        self.label_PortA_Paudrate.setText(_translate("widget_Setting", "波特率"))
        self.comboBox_PortA_Paudrate.setItemText(0, _translate("widget_Setting", "9600"))
        self.comboBox_PortA_Paudrate.setItemText(1, _translate("widget_Setting", "19200"))
        self.comboBox_PortA_Paudrate.setItemText(2, _translate("widget_Setting", "38400"))
        self.comboBox_PortA_Paudrate.setItemText(3, _translate("widget_Setting", "57600"))
        self.comboBox_PortA_Paudrate.setItemText(4, _translate("widget_Setting", "115200"))
        self.groupBox_2.setTitle(_translate("widget_Setting", "Port B 连接数字板"))
        self.label_PortB_Id.setText(_translate("widget_Setting", "串口"))
        self.comboBox_PortB_Id.setItemText(0, _translate("widget_Setting", "COM1"))
        self.comboBox_PortB_Id.setItemText(1, _translate("widget_Setting", "COM2"))
        self.comboBox_PortB_Id.setItemText(2, _translate("widget_Setting", "COM3"))
        self.comboBox_PortB_Id.setItemText(3, _translate("widget_Setting", "COM4"))
        self.comboBox_PortB_Id.setItemText(4, _translate("widget_Setting", "COM5"))
        self.comboBox_PortB_Id.setItemText(5, _translate("widget_Setting", "COM6"))
        self.comboBox_PortB_Id.setItemText(6, _translate("widget_Setting", "COM7"))
        self.comboBox_PortB_Id.setItemText(7, _translate("widget_Setting", "COM8"))
        self.comboBox_PortB_Id.setItemText(8, _translate("widget_Setting", "COM9"))
        self.comboBox_PortB_Id.setItemText(9, _translate("widget_Setting", "COM10"))
        self.label_PortB_Paudrate.setText(_translate("widget_Setting", "波特率"))
        self.comboBox_PortB_Paudrate.setItemText(0, _translate("widget_Setting", "9600"))
        self.comboBox_PortB_Paudrate.setItemText(1, _translate("widget_Setting", "19200"))
        self.comboBox_PortB_Paudrate.setItemText(2, _translate("widget_Setting", "38400"))
        self.comboBox_PortB_Paudrate.setItemText(3, _translate("widget_Setting", "57600"))
        self.comboBox_PortB_Paudrate.setItemText(4, _translate("widget_Setting", "115200"))
        self.groupBox_4.setTitle(_translate("widget_Setting", "Port C 连接模拟板"))
        self.label_PortC_Id.setText(_translate("widget_Setting", "串口"))
        self.comboBox_PortC_Id.setItemText(0, _translate("widget_Setting", "COM1"))
        self.comboBox_PortC_Id.setItemText(1, _translate("widget_Setting", "COM2"))
        self.comboBox_PortC_Id.setItemText(2, _translate("widget_Setting", "COM3"))
        self.comboBox_PortC_Id.setItemText(3, _translate("widget_Setting", "COM4"))
        self.comboBox_PortC_Id.setItemText(4, _translate("widget_Setting", "COM5"))
        self.comboBox_PortC_Id.setItemText(5, _translate("widget_Setting", "COM6"))
        self.comboBox_PortC_Id.setItemText(6, _translate("widget_Setting", "COM7"))
        self.comboBox_PortC_Id.setItemText(7, _translate("widget_Setting", "COM8"))
        self.comboBox_PortC_Id.setItemText(8, _translate("widget_Setting", "COM9"))
        self.comboBox_PortC_Id.setItemText(9, _translate("widget_Setting", "COM10"))
        self.label_PortC_Paudrate.setText(_translate("widget_Setting", "波特率"))
        self.comboBox_PortC_Paudrate.setItemText(0, _translate("widget_Setting", "9600"))
        self.comboBox_PortC_Paudrate.setItemText(1, _translate("widget_Setting", "19200"))
        self.comboBox_PortC_Paudrate.setItemText(2, _translate("widget_Setting", "38400"))
        self.comboBox_PortC_Paudrate.setItemText(3, _translate("widget_Setting", "57600"))
        self.comboBox_PortC_Paudrate.setItemText(4, _translate("widget_Setting", "115200"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Setting = QtWidgets.QWidget()
    ui = Ui_widget_Setting()
    ui.setupUi(widget_Setting)
    widget_Setting.show()
    sys.exit(app.exec_())

