# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calibration.ui'
#
# Created: Sun Apr 23 21:18:36 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_calibration(object):
    def setupUi(self, Dialog_calibration):
        Dialog_calibration.setObjectName("Dialog_calibration")
        Dialog_calibration.resize(694, 518)
        self.line = QtWidgets.QFrame(Dialog_calibration)
        self.line.setGeometry(QtCore.QRect(16, 32, 665, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_2 = QtWidgets.QFrame(Dialog_calibration)
        self.line_2.setGeometry(QtCore.QRect(24, 440, 649, 16))
        self.line_2.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_2.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_2.setObjectName("line_2")
        self.layoutWidget = QtWidgets.QWidget(Dialog_calibration)
        self.layoutWidget.setGeometry(QtCore.QRect(49, 8, 593, 25))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.layoutWidget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget)
        self.label_8.setText("")
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 2, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 3, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 4, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.layoutWidget)
        self.label_9.setText("")
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 5, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 6, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(False)
        font.setWeight(50)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 7, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget)
        self.label_10.setText("")
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 0, 8, 1, 1)
        self.pushButton_back_set = QtWidgets.QPushButton(self.layoutWidget)
        self.pushButton_back_set.setObjectName("pushButton_back_set")
        self.gridLayout.addWidget(self.pushButton_back_set, 0, 9, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_calibration)
        self.layoutWidget1.setGeometry(QtCore.QRect(56, 448, 585, 57))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_show_calibration_result = QtWidgets.QLabel(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(31)
        font.setBold(True)
        font.setWeight(75)
        self.label_show_calibration_result.setFont(font)
        self.label_show_calibration_result.setFrameShadow(QtWidgets.QFrame.Plain)
        self.label_show_calibration_result.setObjectName("label_show_calibration_result")
        self.gridLayout_2.addWidget(self.label_show_calibration_result, 0, 0, 2, 2)
        self.pushButton_2 = QtWidgets.QPushButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_2.setFont(font)
        self.pushButton_2.setObjectName("pushButton_2")
        self.gridLayout_2.addWidget(self.pushButton_2, 0, 2, 2, 1)
        self.pushButton_3 = QtWidgets.QPushButton(self.layoutWidget1)
        self.pushButton_3.setObjectName("pushButton_3")
        self.gridLayout_2.addWidget(self.pushButton_3, 0, 3, 2, 1)
        self.layoutWidget2 = QtWidgets.QWidget(Dialog_calibration)
        self.layoutWidget2.setGeometry(QtCore.QRect(48, 48, 489, 383))
        self.layoutWidget2.setObjectName("layoutWidget2")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget2)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.gridLayout_3 = QtWidgets.QGridLayout()
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout_3.addWidget(self.lineEdit_7, 1, 3, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_24.setObjectName("label_24")
        self.gridLayout_3.addWidget(self.label_24, 1, 5, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_16.setObjectName("label_16")
        self.gridLayout_3.addWidget(self.label_16, 0, 5, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout_3.addWidget(self.lineEdit, 0, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout_3.addWidget(self.lineEdit_4, 0, 12, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_20.setObjectName("label_20")
        self.gridLayout_3.addWidget(self.label_20, 0, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout_3.addWidget(self.lineEdit_3, 0, 9, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_18.setObjectName("label_18")
        self.gridLayout_3.addWidget(self.label_18, 0, 11, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_22.setObjectName("label_22")
        self.gridLayout_3.addWidget(self.label_22, 1, 2, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_17.setObjectName("label_17")
        self.gridLayout_3.addWidget(self.label_17, 0, 8, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout_3.addWidget(self.lineEdit_2, 0, 6, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout_3.addWidget(self.lineEdit_8, 1, 6, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_21.setObjectName("label_21")
        self.gridLayout_3.addWidget(self.label_21, 1, 8, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout_3.addWidget(self.lineEdit_6, 1, 9, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_23.setObjectName("label_23")
        self.gridLayout_3.addWidget(self.label_23, 1, 11, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout_3.addWidget(self.lineEdit_5, 1, 12, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_27.setText("")
        self.label_27.setObjectName("label_27")
        self.gridLayout_3.addWidget(self.label_27, 0, 4, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_28.setText("")
        self.label_28.setObjectName("label_28")
        self.gridLayout_3.addWidget(self.label_28, 0, 7, 1, 1)
        self.label_29 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_29.setText("")
        self.label_29.setObjectName("label_29")
        self.gridLayout_3.addWidget(self.label_29, 0, 10, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_26.setText("")
        self.label_26.setObjectName("label_26")
        self.gridLayout_3.addWidget(self.label_26, 0, 1, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_3.addWidget(self.label_11, 0, 0, 1, 1)
        self.pushButton_5 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_5.setObjectName("pushButton_5")
        self.gridLayout_3.addWidget(self.pushButton_5, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_3)
        self.line_3 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_3.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_3.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_3.setObjectName("line_3")
        self.verticalLayout.addWidget(self.line_3)
        self.gridLayout_4 = QtWidgets.QGridLayout()
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout_4.addWidget(self.lineEdit_9, 1, 3, 1, 1)
        self.label_30 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_30.setObjectName("label_30")
        self.gridLayout_4.addWidget(self.label_30, 1, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_19.setObjectName("label_19")
        self.gridLayout_4.addWidget(self.label_19, 0, 5, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout_4.addWidget(self.lineEdit_10, 0, 3, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout_4.addWidget(self.lineEdit_11, 0, 12, 1, 1)
        self.label_31 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_31.setObjectName("label_31")
        self.gridLayout_4.addWidget(self.label_31, 0, 2, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout_4.addWidget(self.lineEdit_12, 0, 9, 1, 1)
        self.label_32 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_32.setObjectName("label_32")
        self.gridLayout_4.addWidget(self.label_32, 0, 11, 1, 1)
        self.label_33 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_33.setObjectName("label_33")
        self.gridLayout_4.addWidget(self.label_33, 1, 2, 1, 1)
        self.label_34 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_34.setObjectName("label_34")
        self.gridLayout_4.addWidget(self.label_34, 0, 8, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout_4.addWidget(self.lineEdit_13, 0, 6, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout_4.addWidget(self.lineEdit_14, 1, 6, 1, 1)
        self.label_35 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 1, 8, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout_4.addWidget(self.lineEdit_15, 1, 9, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 1, 11, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout_4.addWidget(self.lineEdit_16, 1, 12, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_37.setText("")
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 0, 4, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_38.setText("")
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 0, 7, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_39.setText("")
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 0, 10, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_40.setText("")
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 0, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 0, 0, 1, 1)
        self.pushButton_4 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_4.setObjectName("pushButton_4")
        self.gridLayout_4.addWidget(self.pushButton_4, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_4)
        self.line_4 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_4.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_4.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_4.setObjectName("line_4")
        self.verticalLayout.addWidget(self.line_4)
        self.gridLayout_5 = QtWidgets.QGridLayout()
        self.gridLayout_5.setObjectName("gridLayout_5")
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout_5.addWidget(self.lineEdit_17, 1, 3, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_41.setObjectName("label_41")
        self.gridLayout_5.addWidget(self.label_41, 1, 5, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_42.setObjectName("label_42")
        self.gridLayout_5.addWidget(self.label_42, 0, 5, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout_5.addWidget(self.lineEdit_18, 0, 3, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout_5.addWidget(self.lineEdit_19, 0, 12, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_43.setObjectName("label_43")
        self.gridLayout_5.addWidget(self.label_43, 0, 2, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout_5.addWidget(self.lineEdit_20, 0, 9, 1, 1)
        self.label_44 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_44.setObjectName("label_44")
        self.gridLayout_5.addWidget(self.label_44, 0, 11, 1, 1)
        self.label_45 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_45.setObjectName("label_45")
        self.gridLayout_5.addWidget(self.label_45, 1, 2, 1, 1)
        self.label_46 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_46.setObjectName("label_46")
        self.gridLayout_5.addWidget(self.label_46, 0, 8, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout_5.addWidget(self.lineEdit_21, 0, 6, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout_5.addWidget(self.lineEdit_22, 1, 6, 1, 1)
        self.label_47 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_47.setObjectName("label_47")
        self.gridLayout_5.addWidget(self.label_47, 1, 8, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout_5.addWidget(self.lineEdit_23, 1, 9, 1, 1)
        self.label_48 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_48.setObjectName("label_48")
        self.gridLayout_5.addWidget(self.label_48, 1, 11, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout_5.addWidget(self.lineEdit_24, 1, 12, 1, 1)
        self.label_49 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_49.setText("")
        self.label_49.setObjectName("label_49")
        self.gridLayout_5.addWidget(self.label_49, 0, 4, 1, 1)
        self.label_50 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_50.setText("")
        self.label_50.setObjectName("label_50")
        self.gridLayout_5.addWidget(self.label_50, 0, 7, 1, 1)
        self.label_51 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_51.setText("")
        self.label_51.setObjectName("label_51")
        self.gridLayout_5.addWidget(self.label_51, 0, 10, 1, 1)
        self.label_52 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_52.setText("")
        self.label_52.setObjectName("label_52")
        self.gridLayout_5.addWidget(self.label_52, 0, 1, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_13.setObjectName("label_13")
        self.gridLayout_5.addWidget(self.label_13, 0, 0, 1, 1)
        self.pushButton_6 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_6.setObjectName("pushButton_6")
        self.gridLayout_5.addWidget(self.pushButton_6, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_5)
        self.line_5 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_5.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_5.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_5.setObjectName("line_5")
        self.verticalLayout.addWidget(self.line_5)
        self.gridLayout_6 = QtWidgets.QGridLayout()
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout_6.addWidget(self.lineEdit_25, 1, 3, 1, 1)
        self.label_53 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_53.setObjectName("label_53")
        self.gridLayout_6.addWidget(self.label_53, 1, 5, 1, 1)
        self.label_54 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_54.setObjectName("label_54")
        self.gridLayout_6.addWidget(self.label_54, 0, 5, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout_6.addWidget(self.lineEdit_26, 0, 3, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout_6.addWidget(self.lineEdit_27, 0, 12, 1, 1)
        self.label_55 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_55.setObjectName("label_55")
        self.gridLayout_6.addWidget(self.label_55, 0, 2, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout_6.addWidget(self.lineEdit_28, 0, 9, 1, 1)
        self.label_56 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_56.setObjectName("label_56")
        self.gridLayout_6.addWidget(self.label_56, 0, 11, 1, 1)
        self.label_57 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_57.setObjectName("label_57")
        self.gridLayout_6.addWidget(self.label_57, 1, 2, 1, 1)
        self.label_58 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_58.setObjectName("label_58")
        self.gridLayout_6.addWidget(self.label_58, 0, 8, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout_6.addWidget(self.lineEdit_29, 0, 6, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout_6.addWidget(self.lineEdit_30, 1, 6, 1, 1)
        self.label_59 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_59.setObjectName("label_59")
        self.gridLayout_6.addWidget(self.label_59, 1, 8, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout_6.addWidget(self.lineEdit_31, 1, 9, 1, 1)
        self.label_60 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_60.setObjectName("label_60")
        self.gridLayout_6.addWidget(self.label_60, 1, 11, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout_6.addWidget(self.lineEdit_32, 1, 12, 1, 1)
        self.label_61 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_61.setText("")
        self.label_61.setObjectName("label_61")
        self.gridLayout_6.addWidget(self.label_61, 0, 4, 1, 1)
        self.label_62 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_62.setText("")
        self.label_62.setObjectName("label_62")
        self.gridLayout_6.addWidget(self.label_62, 0, 7, 1, 1)
        self.label_63 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_63.setText("")
        self.label_63.setObjectName("label_63")
        self.gridLayout_6.addWidget(self.label_63, 0, 10, 1, 1)
        self.label_64 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_64.setText("")
        self.label_64.setObjectName("label_64")
        self.gridLayout_6.addWidget(self.label_64, 0, 1, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_14.setObjectName("label_14")
        self.gridLayout_6.addWidget(self.label_14, 0, 0, 1, 1)
        self.pushButton_7 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_7.setObjectName("pushButton_7")
        self.gridLayout_6.addWidget(self.pushButton_7, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_6)
        self.line_6 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_6.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_6.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_6.setObjectName("line_6")
        self.verticalLayout.addWidget(self.line_6)
        self.gridLayout_7 = QtWidgets.QGridLayout()
        self.gridLayout_7.setObjectName("gridLayout_7")
        self.pushButton_8 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_8.setObjectName("pushButton_8")
        self.gridLayout_7.addWidget(self.pushButton_8, 1, 0, 1, 1)
        self.label_70 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_70.setObjectName("label_70")
        self.gridLayout_7.addWidget(self.label_70, 0, 8, 1, 1)
        self.label_69 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_69.setObjectName("label_69")
        self.gridLayout_7.addWidget(self.label_69, 1, 2, 1, 1)
        self.label_68 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_68.setObjectName("label_68")
        self.gridLayout_7.addWidget(self.label_68, 0, 11, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout_7.addWidget(self.lineEdit_36, 0, 9, 1, 1)
        self.label_67 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_67.setObjectName("label_67")
        self.gridLayout_7.addWidget(self.label_67, 0, 2, 1, 1)
        self.label_72 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_72.setObjectName("label_72")
        self.gridLayout_7.addWidget(self.label_72, 1, 11, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout_7.addWidget(self.lineEdit_39, 1, 9, 1, 1)
        self.label_71 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_71.setObjectName("label_71")
        self.gridLayout_7.addWidget(self.label_71, 1, 8, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout_7.addWidget(self.lineEdit_38, 1, 6, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout_7.addWidget(self.lineEdit_37, 0, 6, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_15.setObjectName("label_15")
        self.gridLayout_7.addWidget(self.label_15, 0, 0, 1, 1)
        self.label_76 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_76.setText("")
        self.label_76.setObjectName("label_76")
        self.gridLayout_7.addWidget(self.label_76, 0, 1, 1, 1)
        self.label_75 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_75.setText("")
        self.label_75.setObjectName("label_75")
        self.gridLayout_7.addWidget(self.label_75, 0, 10, 1, 1)
        self.label_74 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_74.setText("")
        self.label_74.setObjectName("label_74")
        self.gridLayout_7.addWidget(self.label_74, 0, 7, 1, 1)
        self.label_73 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_73.setText("")
        self.label_73.setObjectName("label_73")
        self.gridLayout_7.addWidget(self.label_73, 0, 4, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout_7.addWidget(self.lineEdit_40, 1, 12, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout_7.addWidget(self.lineEdit_35, 0, 12, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout_7.addWidget(self.lineEdit_34, 0, 3, 1, 1)
        self.label_66 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_66.setObjectName("label_66")
        self.gridLayout_7.addWidget(self.label_66, 0, 5, 1, 1)
        self.label_65 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_65.setObjectName("label_65")
        self.gridLayout_7.addWidget(self.label_65, 1, 5, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout_7.addWidget(self.lineEdit_33, 1, 3, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_7)
        self.line_7 = QtWidgets.QFrame(self.layoutWidget2)
        self.line_7.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_7.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_7.setObjectName("line_7")
        self.verticalLayout.addWidget(self.line_7)
        self.gridLayout_8 = QtWidgets.QGridLayout()
        self.gridLayout_8.setObjectName("gridLayout_8")
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout_8.addWidget(self.lineEdit_41, 1, 3, 1, 1)
        self.label_77 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_77.setObjectName("label_77")
        self.gridLayout_8.addWidget(self.label_77, 1, 5, 1, 1)
        self.label_78 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_78.setObjectName("label_78")
        self.gridLayout_8.addWidget(self.label_78, 0, 5, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout_8.addWidget(self.lineEdit_42, 0, 3, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout_8.addWidget(self.lineEdit_43, 0, 12, 1, 1)
        self.label_79 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_79.setObjectName("label_79")
        self.gridLayout_8.addWidget(self.label_79, 0, 2, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout_8.addWidget(self.lineEdit_44, 0, 9, 1, 1)
        self.label_80 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_80.setObjectName("label_80")
        self.gridLayout_8.addWidget(self.label_80, 0, 11, 1, 1)
        self.label_81 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_81.setObjectName("label_81")
        self.gridLayout_8.addWidget(self.label_81, 1, 2, 1, 1)
        self.label_82 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_82.setObjectName("label_82")
        self.gridLayout_8.addWidget(self.label_82, 0, 8, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout_8.addWidget(self.lineEdit_45, 0, 6, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout_8.addWidget(self.lineEdit_46, 1, 6, 1, 1)
        self.label_83 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_83.setObjectName("label_83")
        self.gridLayout_8.addWidget(self.label_83, 1, 8, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout_8.addWidget(self.lineEdit_47, 1, 9, 1, 1)
        self.label_84 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_84.setObjectName("label_84")
        self.gridLayout_8.addWidget(self.label_84, 1, 11, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.layoutWidget2)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout_8.addWidget(self.lineEdit_48, 1, 12, 1, 1)
        self.label_85 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_85.setText("")
        self.label_85.setObjectName("label_85")
        self.gridLayout_8.addWidget(self.label_85, 0, 4, 1, 1)
        self.label_86 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_86.setText("")
        self.label_86.setObjectName("label_86")
        self.gridLayout_8.addWidget(self.label_86, 0, 7, 1, 1)
        self.label_87 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_87.setText("")
        self.label_87.setObjectName("label_87")
        self.gridLayout_8.addWidget(self.label_87, 0, 10, 1, 1)
        self.label_88 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_88.setText("")
        self.label_88.setObjectName("label_88")
        self.gridLayout_8.addWidget(self.label_88, 0, 1, 1, 1)
        self.label_89 = QtWidgets.QLabel(self.layoutWidget2)
        self.label_89.setObjectName("label_89")
        self.gridLayout_8.addWidget(self.label_89, 0, 0, 1, 1)
        self.pushButton_9 = QtWidgets.QPushButton(self.layoutWidget2)
        self.pushButton_9.setObjectName("pushButton_9")
        self.gridLayout_8.addWidget(self.pushButton_9, 1, 0, 1, 1)
        self.verticalLayout.addLayout(self.gridLayout_8)

        self.retranslateUi(Dialog_calibration)
        QtCore.QMetaObject.connectSlotsByName(Dialog_calibration)

    def retranslateUi(self, Dialog_calibration):
        _translate = QtCore.QCoreApplication.translate
        Dialog_calibration.setWindowTitle(_translate("Dialog_calibration", "Dialog"))
        self.label.setText(_translate("Dialog_calibration", "Port A <-->"))
        self.label_7.setText(_translate("Dialog_calibration", "COM1"))
        self.label_2.setText(_translate("Dialog_calibration", "Port B <-->"))
        self.label_6.setText(_translate("Dialog_calibration", "COM2"))
        self.label_4.setText(_translate("Dialog_calibration", "校准对象："))
        self.label_5.setText(_translate("Dialog_calibration", "LX 8PT 模块"))
        self.pushButton_back_set.setText(_translate("Dialog_calibration", "返回设置"))
        self.label_show_calibration_result.setText(_translate("Dialog_calibration", "<html><head/><body><p><span style=\" font-weight:400; color:#000000;\">校准结果</span></p></body></html>"))
        self.pushButton_2.setText(_translate("Dialog_calibration", "PushButton"))
        self.pushButton_3.setText(_translate("Dialog_calibration", "PushButton"))
        self.label_24.setText(_translate("Dialog_calibration", "6"))
        self.label_16.setText(_translate("Dialog_calibration", "2"))
        self.label_20.setText(_translate("Dialog_calibration", "1"))
        self.label_18.setText(_translate("Dialog_calibration", "4"))
        self.label_22.setText(_translate("Dialog_calibration", "5"))
        self.label_17.setText(_translate("Dialog_calibration", "3"))
        self.label_21.setText(_translate("Dialog_calibration", "7"))
        self.label_23.setText(_translate("Dialog_calibration", "8"))
        self.label_11.setText(_translate("Dialog_calibration", "实时检测值："))
        self.pushButton_5.setText(_translate("Dialog_calibration", "连接通道..."))
        self.label_30.setText(_translate("Dialog_calibration", "6"))
        self.label_19.setText(_translate("Dialog_calibration", "2"))
        self.label_31.setText(_translate("Dialog_calibration", "1"))
        self.label_32.setText(_translate("Dialog_calibration", "4"))
        self.label_33.setText(_translate("Dialog_calibration", "5"))
        self.label_34.setText(_translate("Dialog_calibration", "3"))
        self.label_35.setText(_translate("Dialog_calibration", "7"))
        self.label_36.setText(_translate("Dialog_calibration", "8"))
        self.label_12.setText(_translate("Dialog_calibration", "300Ω基准："))
        self.pushButton_4.setText(_translate("Dialog_calibration", "基准读取..."))
        self.label_41.setText(_translate("Dialog_calibration", "6"))
        self.label_42.setText(_translate("Dialog_calibration", "2"))
        self.label_43.setText(_translate("Dialog_calibration", "1"))
        self.label_44.setText(_translate("Dialog_calibration", "4"))
        self.label_45.setText(_translate("Dialog_calibration", "5"))
        self.label_46.setText(_translate("Dialog_calibration", "3"))
        self.label_47.setText(_translate("Dialog_calibration", "7"))
        self.label_48.setText(_translate("Dialog_calibration", "8"))
        self.label_13.setText(_translate("Dialog_calibration", "100Ω基准："))
        self.pushButton_6.setText(_translate("Dialog_calibration", "基准读取..."))
        self.label_53.setText(_translate("Dialog_calibration", "6"))
        self.label_54.setText(_translate("Dialog_calibration", "2"))
        self.label_55.setText(_translate("Dialog_calibration", "1"))
        self.label_56.setText(_translate("Dialog_calibration", "4"))
        self.label_57.setText(_translate("Dialog_calibration", "5"))
        self.label_58.setText(_translate("Dialog_calibration", "3"))
        self.label_59.setText(_translate("Dialog_calibration", "7"))
        self.label_60.setText(_translate("Dialog_calibration", "8"))
        self.label_14.setText(_translate("Dialog_calibration", "68Ω检测："))
        self.pushButton_7.setText(_translate("Dialog_calibration", "检测读取..."))
        self.pushButton_8.setText(_translate("Dialog_calibration", "检测读取..."))
        self.label_70.setText(_translate("Dialog_calibration", "3"))
        self.label_69.setText(_translate("Dialog_calibration", "5"))
        self.label_68.setText(_translate("Dialog_calibration", "4"))
        self.label_67.setText(_translate("Dialog_calibration", "1"))
        self.label_72.setText(_translate("Dialog_calibration", "8"))
        self.label_71.setText(_translate("Dialog_calibration", "7"))
        self.label_15.setText(_translate("Dialog_calibration", "150Ω检测："))
        self.label_66.setText(_translate("Dialog_calibration", "2"))
        self.label_65.setText(_translate("Dialog_calibration", "6"))
        self.label_77.setText(_translate("Dialog_calibration", "6"))
        self.label_78.setText(_translate("Dialog_calibration", "2"))
        self.label_79.setText(_translate("Dialog_calibration", "1"))
        self.label_80.setText(_translate("Dialog_calibration", "4"))
        self.label_81.setText(_translate("Dialog_calibration", "5"))
        self.label_82.setText(_translate("Dialog_calibration", "3"))
        self.label_83.setText(_translate("Dialog_calibration", "7"))
        self.label_84.setText(_translate("Dialog_calibration", "8"))
        self.label_89.setText(_translate("Dialog_calibration", "200Ω检测："))
        self.pushButton_9.setText(_translate("Dialog_calibration", "检测读取..."))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_calibration = QtWidgets.QDialog()
    ui = Ui_Dialog_calibration()
    ui.setupUi(Dialog_calibration)
    Dialog_calibration.show()
    sys.exit(app.exec_())

