# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'downlod.ui'
#
# Created: Sun Apr 23 21:18:36 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_downloadwindow(object):
    def setupUi(self, downloadwindow):
        downloadwindow.setObjectName("downloadwindow")
        downloadwindow.resize(882, 497)
        self.textBrowser = QtWidgets.QTextBrowser(downloadwindow)
        self.textBrowser.setGeometry(QtCore.QRect(520, 20, 351, 391))
        self.textBrowser.setObjectName("textBrowser")
        self.splitter = QtWidgets.QSplitter(downloadwindow)
        self.splitter.setGeometry(QtCore.QRect(30, 20, 451, 391))
        self.splitter.setOrientation(QtCore.Qt.Vertical)
        self.splitter.setObjectName("splitter")
        self.widget = QtWidgets.QWidget(self.splitter)
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.comboBox_select_module = QtWidgets.QComboBox(self.widget)
        self.comboBox_select_module.setObjectName("comboBox_select_module")
        self.gridLayout.addWidget(self.comboBox_select_module, 0, 1, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 1, 0, 1, 1)
        self.comboBox_select_com = QtWidgets.QComboBox(self.widget)
        self.comboBox_select_com.setObjectName("comboBox_select_com")
        self.gridLayout.addWidget(self.comboBox_select_com, 1, 1, 1, 1)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 2, 0, 1, 1)
        self.comboBox_select_paudrate = QtWidgets.QComboBox(self.widget)
        self.comboBox_select_paudrate.setObjectName("comboBox_select_paudrate")
        self.gridLayout.addWidget(self.comboBox_select_paudrate, 2, 1, 1, 1)
        self.widget1 = QtWidgets.QWidget(self.splitter)
        self.widget1.setObjectName("widget1")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.widget1)
        self.gridLayout_3.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.gridLayout_2 = QtWidgets.QGridLayout()
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label_6 = QtWidgets.QLabel(self.widget1)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 2, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.widget1)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 1, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(self.widget1)
        self.label_4.setObjectName("label_4")
        self.gridLayout_2.addWidget(self.label_4, 0, 0, 1, 1)
        self.gridLayout_3.addLayout(self.gridLayout_2, 0, 0, 3, 1)
        self.lineEdit_biospath = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_biospath.setObjectName("lineEdit_biospath")
        self.gridLayout_3.addWidget(self.lineEdit_biospath, 0, 1, 1, 1)
        self.toolButton_biospath = QtWidgets.QToolButton(self.widget1)
        self.toolButton_biospath.setToolButtonStyle(QtCore.Qt.ToolButtonIconOnly)
        self.toolButton_biospath.setObjectName("toolButton_biospath")
        self.gridLayout_3.addWidget(self.toolButton_biospath, 0, 2, 1, 1)
        self.lineEdit_framepath = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_framepath.setObjectName("lineEdit_framepath")
        self.gridLayout_3.addWidget(self.lineEdit_framepath, 1, 1, 1, 1)
        self.toolButton_framepath = QtWidgets.QToolButton(self.widget1)
        self.toolButton_framepath.setObjectName("toolButton_framepath")
        self.gridLayout_3.addWidget(self.toolButton_framepath, 1, 2, 1, 1)
        self.lineEdit_ladderpath = QtWidgets.QLineEdit(self.widget1)
        self.lineEdit_ladderpath.setObjectName("lineEdit_ladderpath")
        self.gridLayout_3.addWidget(self.lineEdit_ladderpath, 2, 1, 1, 1)
        self.toolButton_ladderpath = QtWidgets.QToolButton(self.widget1)
        self.toolButton_ladderpath.setObjectName("toolButton_ladderpath")
        self.gridLayout_3.addWidget(self.toolButton_ladderpath, 2, 2, 1, 1)
        self.widget2 = QtWidgets.QWidget(self.splitter)
        self.widget2.setObjectName("widget2")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.widget2)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_7 = QtWidgets.QLabel(self.widget2)
        self.label_7.setObjectName("label_7")
        self.gridLayout_4.addWidget(self.label_7, 1, 0, 1, 1)
        self.lineEdit_show_product_times = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_show_product_times.setEnabled(False)
        self.lineEdit_show_product_times.setObjectName("lineEdit_show_product_times")
        self.gridLayout_4.addWidget(self.lineEdit_show_product_times, 2, 1, 1, 1)
        self.lineEdit_show_harderversion = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_show_harderversion.setEnabled(False)
        self.lineEdit_show_harderversion.setObjectName("lineEdit_show_harderversion")
        self.gridLayout_4.addWidget(self.lineEdit_show_harderversion, 1, 1, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget2)
        self.label_8.setObjectName("label_8")
        self.gridLayout_4.addWidget(self.label_8, 2, 0, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget2)
        self.label_10.setObjectName("label_10")
        self.gridLayout_4.addWidget(self.label_10, 4, 0, 1, 1)
        self.lineEdit_show_download_time = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_show_download_time.setEnabled(False)
        self.lineEdit_show_download_time.setObjectName("lineEdit_show_download_time")
        self.gridLayout_4.addWidget(self.lineEdit_show_download_time, 6, 1, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget2)
        self.label_12.setObjectName("label_12")
        self.gridLayout_4.addWidget(self.label_12, 6, 0, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget2)
        self.label_11.setObjectName("label_11")
        self.gridLayout_4.addWidget(self.label_11, 5, 0, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget2)
        self.label_9.setObjectName("label_9")
        self.gridLayout_4.addWidget(self.label_9, 3, 0, 1, 1)
        self.lineEdit_show_serial_number = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_show_serial_number.setEnabled(False)
        self.lineEdit_show_serial_number.setObjectName("lineEdit_show_serial_number")
        self.gridLayout_4.addWidget(self.lineEdit_show_serial_number, 4, 1, 1, 1)
        self.lineEdit_showothflag = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_showothflag.setEnabled(False)
        self.lineEdit_showothflag.setObjectName("lineEdit_showothflag")
        self.gridLayout_4.addWidget(self.lineEdit_showothflag, 3, 1, 1, 1)
        self.lineEdit_show_downloadtimes = QtWidgets.QLineEdit(self.widget2)
        self.lineEdit_show_downloadtimes.setEnabled(False)
        self.lineEdit_show_downloadtimes.setObjectName("lineEdit_show_downloadtimes")
        self.gridLayout_4.addWidget(self.lineEdit_show_downloadtimes, 5, 1, 1, 1)
        self.splitter_2 = QtWidgets.QSplitter(self.widget2)
        self.splitter_2.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_2.setObjectName("splitter_2")
        self.splitter_3 = QtWidgets.QSplitter(self.splitter_2)
        self.splitter_3.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_3.setObjectName("splitter_3")
        self.pushButton_start_download = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_start_download.setObjectName("pushButton_start_download")
        self.pushButton_stop_download = QtWidgets.QPushButton(self.splitter_3)
        self.pushButton_stop_download.setObjectName("pushButton_stop_download")
        self.gridLayout_4.addWidget(self.splitter_2, 0, 1, 1, 1)
        self.splitter_4 = QtWidgets.QSplitter(downloadwindow)
        self.splitter_4.setGeometry(QtCore.QRect(30, 420, 841, 64))
        self.splitter_4.setOrientation(QtCore.Qt.Horizontal)
        self.splitter_4.setObjectName("splitter_4")
        self.download_flag = QtWidgets.QLabel(self.splitter_4)
        self.download_flag.setEnabled(False)
        font = QtGui.QFont()
        font.setFamily("宋体")
        font.setPointSize(48)
        font.setBold(True)
        font.setWeight(75)
        self.download_flag.setFont(font)
        self.download_flag.setAutoFillBackground(True)
        self.download_flag.setObjectName("download_flag")
        self.pushButton_start_download_2 = QtWidgets.QPushButton(self.splitter_4)
        self.pushButton_start_download_2.setObjectName("pushButton_start_download_2")

        self.retranslateUi(downloadwindow)
        self.toolButton_biospath.clicked.connect(self.lineEdit_biospath.close)
        QtCore.QMetaObject.connectSlotsByName(downloadwindow)

    def retranslateUi(self, downloadwindow):
        _translate = QtCore.QCoreApplication.translate
        downloadwindow.setWindowTitle(_translate("downloadwindow", "Dialog"))
        self.label.setText(_translate("downloadwindow", "选择机型"))
        self.label_2.setText(_translate("downloadwindow", "选择串口"))
        self.label_3.setText(_translate("downloadwindow", "串口波特率"))
        self.label_6.setText(_translate("downloadwindow", "梯形图"))
        self.label_5.setText(_translate("downloadwindow", "固件"))
        self.label_4.setText(_translate("downloadwindow", "BIOS"))
        self.lineEdit_biospath.setText(_translate("downloadwindow", "Bios Path"))
        self.toolButton_biospath.setText(_translate("downloadwindow", "..."))
        self.toolButton_framepath.setText(_translate("downloadwindow", "..."))
        self.toolButton_ladderpath.setText(_translate("downloadwindow", "..."))
        self.label_7.setText(_translate("downloadwindow", "硬件版本"))
        self.label_8.setText(_translate("downloadwindow", "生产批次"))
        self.label_10.setText(_translate("downloadwindow", "序列号"))
        self.label_12.setText(_translate("downloadwindow", "单次下载时间"))
        self.label_11.setText(_translate("downloadwindow", "下载次数"))
        self.label_9.setText(_translate("downloadwindow", "其他标识"))
        self.pushButton_start_download.setText(_translate("downloadwindow", "开始下载"))
        self.pushButton_stop_download.setText(_translate("downloadwindow", "停止"))
        self.download_flag.setText(_translate("downloadwindow", "下载状态"))
        self.pushButton_start_download_2.setText(_translate("downloadwindow", "下一步：校准"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    downloadwindow = QtWidgets.QDialog()
    ui = Ui_downloadwindow()
    ui.setupUi(downloadwindow)
    downloadwindow.show()
    sys.exit(app.exec_())

