# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'set.ui'
#
# Created: Sun Apr 23 21:18:37 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog_Set(object):
    def setupUi(self, Dialog_Set):
        Dialog_Set.setObjectName("Dialog_Set")
        Dialog_Set.resize(690, 346)
        self.pushButton_Open_Port = QtWidgets.QPushButton(Dialog_Set)
        self.pushButton_Open_Port.setGeometry(QtCore.QRect(184, 264, 185, 57))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Open_Port.setFont(font)
        self.pushButton_Open_Port.setObjectName("pushButton_Open_Port")
        self.pushButton_Go_Calibration = QtWidgets.QPushButton(Dialog_Set)
        self.pushButton_Go_Calibration.setGeometry(QtCore.QRect(456, 264, 185, 57))
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.pushButton_Go_Calibration.setFont(font)
        self.pushButton_Go_Calibration.setObjectName("pushButton_Go_Calibration")
        self.layoutWidget = QtWidgets.QWidget(Dialog_Set)
        self.layoutWidget.setGeometry(QtCore.QRect(48, 56, 321, 161))
        self.layoutWidget.setObjectName("layoutWidget")
        self.gridLayout_Portset = QtWidgets.QGridLayout(self.layoutWidget)
        self.gridLayout_Portset.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Portset.setObjectName("gridLayout_Portset")
        self.label_PortB_Paudrate = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB_Paudrate.setObjectName("label_PortB_Paudrate")
        self.gridLayout_Portset.addWidget(self.label_PortB_Paudrate, 4, 3, 1, 1)
        self.comboBox_PortB_Parity = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortB_Parity.setObjectName("comboBox_PortB_Parity")
        self.comboBox_PortB_Parity.addItem("")
        self.comboBox_PortB_Parity.addItem("")
        self.comboBox_PortB_Parity.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortB_Parity, 6, 4, 1, 1)
        self.label_PortA_Datasize = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortA_Datasize.setObjectName("label_PortA_Datasize")
        self.gridLayout_Portset.addWidget(self.label_PortA_Datasize, 5, 0, 1, 1)
        self.label_PortA_Stopbits = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortA_Stopbits.setObjectName("label_PortA_Stopbits")
        self.gridLayout_Portset.addWidget(self.label_PortA_Stopbits, 8, 0, 1, 1)
        self.comboBox_PortA_Stopbits = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortA_Stopbits.setObjectName("comboBox_PortA_Stopbits")
        self.comboBox_PortA_Stopbits.addItem("")
        self.comboBox_PortA_Stopbits.addItem("")
        self.comboBox_PortA_Stopbits.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortA_Stopbits, 8, 1, 1, 1)
        self.comboBox_PortB_Datasize = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortB_Datasize.setObjectName("comboBox_PortB_Datasize")
        self.comboBox_PortB_Datasize.addItem("")
        self.comboBox_PortB_Datasize.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortB_Datasize, 5, 4, 1, 1)
        self.label_PortB_Datasize = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB_Datasize.setObjectName("label_PortB_Datasize")
        self.gridLayout_Portset.addWidget(self.label_PortB_Datasize, 5, 3, 1, 1)
        self.label_PortB_Stopbits = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB_Stopbits.setObjectName("label_PortB_Stopbits")
        self.gridLayout_Portset.addWidget(self.label_PortB_Stopbits, 8, 3, 1, 1)
        self.comboBox_PortA_Datasize = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortA_Datasize.setObjectName("comboBox_PortA_Datasize")
        self.comboBox_PortA_Datasize.addItem("")
        self.comboBox_PortA_Datasize.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortA_Datasize, 5, 1, 1, 1)
        self.label_PortB_Parity = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB_Parity.setObjectName("label_PortB_Parity")
        self.gridLayout_Portset.addWidget(self.label_PortB_Parity, 6, 3, 1, 1)
        self.comboBox_PortB_Stopbits = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortB_Stopbits.setObjectName("comboBox_PortB_Stopbits")
        self.comboBox_PortB_Stopbits.addItem("")
        self.comboBox_PortB_Stopbits.addItem("")
        self.comboBox_PortB_Stopbits.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortB_Stopbits, 8, 4, 1, 1)
        self.comboBox_PortA_Parity = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortA_Parity.setObjectName("comboBox_PortA_Parity")
        self.comboBox_PortA_Parity.addItem("")
        self.comboBox_PortA_Parity.addItem("")
        self.comboBox_PortA_Parity.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortA_Parity, 6, 1, 1, 1)
        self.label_PortA_Parity = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortA_Parity.setObjectName("label_PortA_Parity")
        self.gridLayout_Portset.addWidget(self.label_PortA_Parity, 6, 0, 1, 1)
        self.label_PortB_Id = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB_Id.setObjectName("label_PortB_Id")
        self.gridLayout_Portset.addWidget(self.label_PortB_Id, 2, 3, 1, 1)
        self.comboBox_PortB_Id = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortB_Id.setObjectName("comboBox_PortB_Id")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.comboBox_PortB_Id.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortB_Id, 2, 4, 1, 1)
        self.label_PortA_Paudrate = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortA_Paudrate.setObjectName("label_PortA_Paudrate")
        self.gridLayout_Portset.addWidget(self.label_PortA_Paudrate, 4, 0, 1, 1)
        self.label_PortA_Id = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortA_Id.setObjectName("label_PortA_Id")
        self.gridLayout_Portset.addWidget(self.label_PortA_Id, 2, 0, 1, 1)
        self.comboBox_PortA_Id = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortA_Id.setObjectName("comboBox_PortA_Id")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.comboBox_PortA_Id.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortA_Id, 2, 1, 1, 1)
        self.label_PortA = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortA.setObjectName("label_PortA")
        self.gridLayout_Portset.addWidget(self.label_PortA, 0, 0, 1, 2)
        self.label_PortB_Id_2 = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB_Id_2.setText("")
        self.label_PortB_Id_2.setObjectName("label_PortB_Id_2")
        self.gridLayout_Portset.addWidget(self.label_PortB_Id_2, 2, 2, 1, 1)
        self.label_PortB = QtWidgets.QLabel(self.layoutWidget)
        self.label_PortB.setObjectName("label_PortB")
        self.gridLayout_Portset.addWidget(self.label_PortB, 0, 3, 1, 2)
        self.comboBox_PortA_Paudrate = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortA_Paudrate.setObjectName("comboBox_PortA_Paudrate")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.comboBox_PortA_Paudrate.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortA_Paudrate, 4, 1, 1, 1)
        self.comboBox_PortB_Paudrate = QtWidgets.QComboBox(self.layoutWidget)
        self.comboBox_PortB_Paudrate.setObjectName("comboBox_PortB_Paudrate")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.comboBox_PortB_Paudrate.addItem("")
        self.gridLayout_Portset.addWidget(self.comboBox_PortB_Paudrate, 4, 4, 1, 1)
        self.layoutWidget1 = QtWidgets.QWidget(Dialog_Set)
        self.layoutWidget1.setGeometry(QtCore.QRect(456, 56, 193, 161))
        self.layoutWidget1.setObjectName("layoutWidget1")
        self.gridLayout_Moduename = QtWidgets.QGridLayout(self.layoutWidget1)
        self.gridLayout_Moduename.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_Moduename.setObjectName("gridLayout_Moduename")
        self.radioButton_Select_8pt = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Select_8pt.setFont(font)
        self.radioButton_Select_8pt.setObjectName("radioButton_Select_8pt")
        self.gridLayout_Moduename.addWidget(self.radioButton_Select_8pt, 0, 0, 1, 1)
        self.radioButton_Select_8tc = QtWidgets.QRadioButton(self.layoutWidget1)
        font = QtGui.QFont()
        font.setPointSize(9)
        font.setBold(True)
        font.setWeight(75)
        self.radioButton_Select_8tc.setFont(font)
        self.radioButton_Select_8tc.setObjectName("radioButton_Select_8tc")
        self.gridLayout_Moduename.addWidget(self.radioButton_Select_8tc, 1, 0, 1, 1)
        self.line = QtWidgets.QFrame(Dialog_Set)
        self.line.setGeometry(QtCore.QRect(104, 32, 281, 16))
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.line_8 = QtWidgets.QFrame(Dialog_Set)
        self.line_8.setGeometry(QtCore.QRect(504, 32, 145, 16))
        self.line_8.setFrameShape(QtWidgets.QFrame.HLine)
        self.line_8.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line_8.setObjectName("line_8")
        self.label = QtWidgets.QLabel(Dialog_Set)
        self.label.setGeometry(QtCore.QRect(40, 32, 54, 12))
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Dialog_Set)
        self.label_2.setGeometry(QtCore.QRect(440, 32, 54, 12))
        self.label_2.setObjectName("label_2")

        self.retranslateUi(Dialog_Set)
        QtCore.QMetaObject.connectSlotsByName(Dialog_Set)

    def retranslateUi(self, Dialog_Set):
        _translate = QtCore.QCoreApplication.translate
        Dialog_Set.setWindowTitle(_translate("Dialog_Set", "Dialog"))
        self.pushButton_Open_Port.setText(_translate("Dialog_Set", ">> 打开串口"))
        self.pushButton_Go_Calibration.setText(_translate("Dialog_Set", "进入校准 >>"))
        self.label_PortB_Paudrate.setText(_translate("Dialog_Set", "波特率"))
        self.comboBox_PortB_Parity.setItemText(0, _translate("Dialog_Set", "EVEN"))
        self.comboBox_PortB_Parity.setItemText(1, _translate("Dialog_Set", "ODD"))
        self.comboBox_PortB_Parity.setItemText(2, _translate("Dialog_Set", "NONE"))
        self.label_PortA_Datasize.setText(_translate("Dialog_Set", "数据长度"))
        self.label_PortA_Stopbits.setText(_translate("Dialog_Set", "停止位"))
        self.comboBox_PortA_Stopbits.setItemText(0, _translate("Dialog_Set", "1位"))
        self.comboBox_PortA_Stopbits.setItemText(1, _translate("Dialog_Set", "2位"))
        self.comboBox_PortA_Stopbits.setItemText(2, _translate("Dialog_Set", "无"))
        self.comboBox_PortB_Datasize.setItemText(0, _translate("Dialog_Set", "7位"))
        self.comboBox_PortB_Datasize.setItemText(1, _translate("Dialog_Set", "8位"))
        self.label_PortB_Datasize.setText(_translate("Dialog_Set", "数据长度"))
        self.label_PortB_Stopbits.setText(_translate("Dialog_Set", "停止位"))
        self.comboBox_PortA_Datasize.setItemText(0, _translate("Dialog_Set", "7位"))
        self.comboBox_PortA_Datasize.setItemText(1, _translate("Dialog_Set", "8位"))
        self.label_PortB_Parity.setText(_translate("Dialog_Set", "校验"))
        self.comboBox_PortB_Stopbits.setItemText(0, _translate("Dialog_Set", "1位"))
        self.comboBox_PortB_Stopbits.setItemText(1, _translate("Dialog_Set", "2位"))
        self.comboBox_PortB_Stopbits.setItemText(2, _translate("Dialog_Set", "无"))
        self.comboBox_PortA_Parity.setItemText(0, _translate("Dialog_Set", "EVEN"))
        self.comboBox_PortA_Parity.setItemText(1, _translate("Dialog_Set", "ODD"))
        self.comboBox_PortA_Parity.setItemText(2, _translate("Dialog_Set", "NONE"))
        self.label_PortA_Parity.setText(_translate("Dialog_Set", "校验"))
        self.label_PortB_Id.setText(_translate("Dialog_Set", "端口"))
        self.comboBox_PortB_Id.setItemText(0, _translate("Dialog_Set", "COM1"))
        self.comboBox_PortB_Id.setItemText(1, _translate("Dialog_Set", "COM2"))
        self.comboBox_PortB_Id.setItemText(2, _translate("Dialog_Set", "COM3"))
        self.comboBox_PortB_Id.setItemText(3, _translate("Dialog_Set", "COM4"))
        self.comboBox_PortB_Id.setItemText(4, _translate("Dialog_Set", "COM5"))
        self.comboBox_PortB_Id.setItemText(5, _translate("Dialog_Set", "COM6"))
        self.comboBox_PortB_Id.setItemText(6, _translate("Dialog_Set", "COM7"))
        self.comboBox_PortB_Id.setItemText(7, _translate("Dialog_Set", "COM8"))
        self.comboBox_PortB_Id.setItemText(8, _translate("Dialog_Set", "COM9"))
        self.comboBox_PortB_Id.setItemText(9, _translate("Dialog_Set", "COM10"))
        self.label_PortA_Paudrate.setText(_translate("Dialog_Set", "波特率"))
        self.label_PortA_Id.setText(_translate("Dialog_Set", "端口"))
        self.comboBox_PortA_Id.setItemText(0, _translate("Dialog_Set", "COM1"))
        self.comboBox_PortA_Id.setItemText(1, _translate("Dialog_Set", "COM2"))
        self.comboBox_PortA_Id.setItemText(2, _translate("Dialog_Set", "COM3"))
        self.comboBox_PortA_Id.setItemText(3, _translate("Dialog_Set", "COM4"))
        self.comboBox_PortA_Id.setItemText(4, _translate("Dialog_Set", "COM5"))
        self.comboBox_PortA_Id.setItemText(5, _translate("Dialog_Set", "COM6"))
        self.comboBox_PortA_Id.setItemText(6, _translate("Dialog_Set", "COM7"))
        self.comboBox_PortA_Id.setItemText(7, _translate("Dialog_Set", "COM8"))
        self.comboBox_PortA_Id.setItemText(8, _translate("Dialog_Set", "COM9"))
        self.comboBox_PortA_Id.setItemText(9, _translate("Dialog_Set", "COM10"))
        self.label_PortA.setText(_translate("Dialog_Set", "Port A 连接被测板"))
        self.label_PortB.setText(_translate("Dialog_Set", "Port B 连接工装"))
        self.comboBox_PortA_Paudrate.setItemText(0, _translate("Dialog_Set", "9600"))
        self.comboBox_PortA_Paudrate.setItemText(1, _translate("Dialog_Set", "19200"))
        self.comboBox_PortA_Paudrate.setItemText(2, _translate("Dialog_Set", "38400"))
        self.comboBox_PortA_Paudrate.setItemText(3, _translate("Dialog_Set", "57600"))
        self.comboBox_PortA_Paudrate.setItemText(4, _translate("Dialog_Set", "115200"))
        self.comboBox_PortB_Paudrate.setItemText(0, _translate("Dialog_Set", "9600"))
        self.comboBox_PortB_Paudrate.setItemText(1, _translate("Dialog_Set", "19200"))
        self.comboBox_PortB_Paudrate.setItemText(2, _translate("Dialog_Set", "38400"))
        self.comboBox_PortB_Paudrate.setItemText(3, _translate("Dialog_Set", "57600"))
        self.comboBox_PortB_Paudrate.setItemText(4, _translate("Dialog_Set", "115200"))
        self.radioButton_Select_8pt.setText(_translate("Dialog_Set", "LX 8PT 模块"))
        self.radioButton_Select_8tc.setText(_translate("Dialog_Set", "LX 8TC 模块"))
        self.label.setText(_translate("Dialog_Set", "串口设置"))
        self.label_2.setText(_translate("Dialog_Set", "校准对象"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Dialog_Set = QtWidgets.QDialog()
    ui = Ui_Dialog_Set()
    ui.setupUi(Dialog_Set)
    Dialog_Set.show()
    sys.exit(app.exec_())

