# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'static_box.ui'
#
# Created: Tue May  9 00:53:19 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(1101, 576)
        self.stackedWidget = QtWidgets.QStackedWidget(Form)
        self.stackedWidget.setGeometry(QtCore.QRect(8, 16, 865, 377))
        self.stackedWidget.setObjectName("stackedWidget")
        self.page = QtWidgets.QWidget()
        self.page.setObjectName("page")
        self.groupBox = QtWidgets.QGroupBox(self.page)
        self.groupBox.setGeometry(QtCore.QRect(8, 0, 825, 377))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.layoutWidget = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget.setGeometry(QtCore.QRect(184, 24, 153, 273))
        self.layoutWidget.setObjectName("layoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.layoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label_1 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_1.setFont(font)
        self.label_1.setObjectName("label_1")
        self.verticalLayout.addWidget(self.label_1)
        self.label_2 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.verticalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.verticalLayout.addWidget(self.label_3)
        self.label_4 = QtWidgets.QLabel(self.layoutWidget)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.verticalLayout.addWidget(self.label_4)
        self.layoutWidget_2 = QtWidgets.QWidget(self.groupBox)
        self.layoutWidget_2.setGeometry(QtCore.QRect(360, 24, 321, 273))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.layoutWidget_2)
        self.verticalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_Module_Type = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Module_Type.setFont(font)
        self.label_Module_Type.setObjectName("label_Module_Type")
        self.verticalLayout_2.addWidget(self.label_Module_Type)
        self.label_Object_Type = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Object_Type.setFont(font)
        self.label_Object_Type.setObjectName("label_Object_Type")
        self.verticalLayout_2.addWidget(self.label_Object_Type)
        self.label_Hard_Detection_Code = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Hard_Detection_Code.setFont(font)
        self.label_Hard_Detection_Code.setObjectName("label_Hard_Detection_Code")
        self.verticalLayout_2.addWidget(self.label_Hard_Detection_Code)
        self.label_Error = QtWidgets.QLabel(self.layoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(20)
        font.setBold(True)
        font.setWeight(75)
        self.label_Error.setFont(font)
        self.label_Error.setObjectName("label_Error")
        self.verticalLayout_2.addWidget(self.label_Error)
        self.progressBar_Calibration = QtWidgets.QProgressBar(self.groupBox)
        self.progressBar_Calibration.setGeometry(QtCore.QRect(32, 320, 761, 41))
        self.progressBar_Calibration.setStyleSheet("background-color: #1a1a1a;\n"
"")
        self.progressBar_Calibration.setProperty("value", 50)
        self.progressBar_Calibration.setAlignment(QtCore.Qt.AlignLeading|QtCore.Qt.AlignLeft|QtCore.Qt.AlignVCenter)
        self.progressBar_Calibration.setTextVisible(False)
        self.progressBar_Calibration.setOrientation(QtCore.Qt.Horizontal)
        self.progressBar_Calibration.setInvertedAppearance(False)
        self.progressBar_Calibration.setObjectName("progressBar_Calibration")
        self.stackedWidget.addWidget(self.page)
        self.page_2 = QtWidgets.QWidget()
        self.page_2.setObjectName("page_2")
        self.groupBox_2 = QtWidgets.QGroupBox(self.page_2)
        self.groupBox_2.setGeometry(QtCore.QRect(0, 0, 833, 377))
        self.groupBox_2.setTitle("")
        self.groupBox_2.setObjectName("groupBox_2")
        self.layoutWidget_3 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_3.setGeometry(QtCore.QRect(16, 56, 801, 33))
        self.layoutWidget_3.setObjectName("layoutWidget_3")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.layoutWidget_3)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.label_35 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_35.setMinimumSize(QtCore.QSize(86, 0))
        self.label_35.setAlignment(QtCore.Qt.AlignCenter)
        self.label_35.setObjectName("label_35")
        self.gridLayout_4.addWidget(self.label_35, 0, 0, 1, 1)
        self.label_36 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_36.setText("")
        self.label_36.setAlignment(QtCore.Qt.AlignCenter)
        self.label_36.setObjectName("label_36")
        self.gridLayout_4.addWidget(self.label_36, 0, 1, 1, 1)
        self.label_37 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_37.setText("")
        self.label_37.setAlignment(QtCore.Qt.AlignCenter)
        self.label_37.setObjectName("label_37")
        self.gridLayout_4.addWidget(self.label_37, 0, 2, 1, 1)
        self.label_38 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_38.setText("")
        self.label_38.setAlignment(QtCore.Qt.AlignCenter)
        self.label_38.setObjectName("label_38")
        self.gridLayout_4.addWidget(self.label_38, 0, 3, 1, 1)
        self.label_39 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_39.setText("")
        self.label_39.setAlignment(QtCore.Qt.AlignCenter)
        self.label_39.setObjectName("label_39")
        self.gridLayout_4.addWidget(self.label_39, 0, 4, 1, 1)
        self.label_40 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_40.setText("")
        self.label_40.setAlignment(QtCore.Qt.AlignCenter)
        self.label_40.setObjectName("label_40")
        self.gridLayout_4.addWidget(self.label_40, 0, 5, 1, 1)
        self.label_41 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_41.setText("")
        self.label_41.setAlignment(QtCore.Qt.AlignCenter)
        self.label_41.setObjectName("label_41")
        self.gridLayout_4.addWidget(self.label_41, 0, 6, 1, 1)
        self.label_42 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_42.setText("")
        self.label_42.setAlignment(QtCore.Qt.AlignCenter)
        self.label_42.setObjectName("label_42")
        self.gridLayout_4.addWidget(self.label_42, 0, 7, 1, 1)
        self.label_43 = QtWidgets.QLabel(self.layoutWidget_3)
        self.label_43.setText("")
        self.label_43.setAlignment(QtCore.Qt.AlignCenter)
        self.label_43.setObjectName("label_43")
        self.gridLayout_4.addWidget(self.label_43, 0, 8, 1, 1)
        self.layoutWidget_4 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_4.setGeometry(QtCore.QRect(16, 96, 801, 265))
        self.layoutWidget_4.setObjectName("layoutWidget_4")
        self.gridLayout = QtWidgets.QGridLayout(self.layoutWidget_4)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label_9 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_9.setMinimumSize(QtCore.QSize(86, 0))
        self.label_9.setAlignment(QtCore.Qt.AlignCenter)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 0, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 0, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 0, 2, 1, 1)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 0, 3, 1, 1)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 0, 4, 1, 1)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 0, 5, 1, 1)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 0, 6, 1, 1)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 0, 7, 1, 1)
        self.label_20 = QtWidgets.QLabel(self.layoutWidget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label_20.sizePolicy().hasHeightForWidth())
        self.label_20.setSizePolicy(sizePolicy)
        self.label_20.setMinimumSize(QtCore.QSize(83, 0))
        self.label_20.setAlignment(QtCore.Qt.AlignCenter)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 0, 8, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_10.setAlignment(QtCore.Qt.AlignCenter)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 1, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 1, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 1, 2, 1, 1)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 1, 3, 1, 1)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 1, 4, 1, 1)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout.addWidget(self.lineEdit_24, 1, 5, 1, 1)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout.addWidget(self.lineEdit_45, 1, 6, 1, 1)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout.addWidget(self.lineEdit_51, 1, 7, 1, 1)
        self.label_18 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_18.setAlignment(QtCore.Qt.AlignCenter)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 1, 8, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_12.setAlignment(QtCore.Qt.AlignCenter)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 2, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 2, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 2, 2, 1, 1)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout.addWidget(self.lineEdit_34, 2, 3, 1, 1)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout.addWidget(self.lineEdit_35, 2, 4, 1, 1)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout.addWidget(self.lineEdit_40, 2, 5, 1, 1)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout.addWidget(self.lineEdit_46, 2, 6, 1, 1)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout.addWidget(self.lineEdit_52, 2, 7, 1, 1)
        self.label_21 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_21.setAlignment(QtCore.Qt.AlignCenter)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 2, 8, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_11.setAlignment(QtCore.Qt.AlignCenter)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 3, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 3, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 3, 2, 1, 1)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 3, 3, 1, 1)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 3, 4, 1, 1)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 3, 5, 1, 1)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 3, 6, 1, 1)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 3, 7, 1, 1)
        self.label_22 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_22.setAlignment(QtCore.Qt.AlignCenter)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 3, 8, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_13.setAlignment(QtCore.Qt.AlignCenter)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 4, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 4, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout.addWidget(self.lineEdit_27, 4, 2, 1, 1)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout.addWidget(self.lineEdit_32, 4, 3, 1, 1)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout.addWidget(self.lineEdit_36, 4, 4, 1, 1)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout.addWidget(self.lineEdit_41, 4, 5, 1, 1)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout.addWidget(self.lineEdit_47, 4, 6, 1, 1)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout.addWidget(self.lineEdit_53, 4, 7, 1, 1)
        self.label_23 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_23.setAlignment(QtCore.Qt.AlignCenter)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 4, 8, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_14.setAlignment(QtCore.Qt.AlignCenter)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 5, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 5, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout.addWidget(self.lineEdit_26, 5, 2, 1, 1)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout.addWidget(self.lineEdit_31, 5, 3, 1, 1)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 5, 4, 1, 1)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout.addWidget(self.lineEdit_42, 5, 5, 1, 1)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout.addWidget(self.lineEdit_48, 5, 6, 1, 1)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout.addWidget(self.lineEdit_54, 5, 7, 1, 1)
        self.label_24 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_24.setAlignment(QtCore.Qt.AlignCenter)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 5, 8, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_15.setAlignment(QtCore.Qt.AlignCenter)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 6, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 6, 1, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 6, 2, 1, 1)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout.addWidget(self.lineEdit_30, 6, 3, 1, 1)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout.addWidget(self.lineEdit_38, 6, 4, 1, 1)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout.addWidget(self.lineEdit_43, 6, 5, 1, 1)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout.addWidget(self.lineEdit_49, 6, 6, 1, 1)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout.addWidget(self.lineEdit_55, 6, 7, 1, 1)
        self.label_25 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_25.setAlignment(QtCore.Qt.AlignCenter)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 6, 8, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_16.setAlignment(QtCore.Qt.AlignCenter)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 7, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 7, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout.addWidget(self.lineEdit_28, 7, 2, 1, 1)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout.addWidget(self.lineEdit_29, 7, 3, 1, 1)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout.addWidget(self.lineEdit_39, 7, 4, 1, 1)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout.addWidget(self.lineEdit_44, 7, 5, 1, 1)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout.addWidget(self.lineEdit_50, 7, 6, 1, 1)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.layoutWidget_4)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout.addWidget(self.lineEdit_56, 7, 7, 1, 1)
        self.label_26 = QtWidgets.QLabel(self.layoutWidget_4)
        self.label_26.setAlignment(QtCore.Qt.AlignCenter)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 7, 8, 1, 1)
        self.layoutWidget_5 = QtWidgets.QWidget(self.groupBox_2)
        self.layoutWidget_5.setGeometry(QtCore.QRect(16, 17, 801, 33))
        self.layoutWidget_5.setObjectName("layoutWidget_5")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.layoutWidget_5)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.label = QtWidgets.QLabel(self.layoutWidget_5)
        self.label.setMinimumSize(QtCore.QSize(86, 0))
        self.label.setAlignment(QtCore.Qt.AlignCenter)
        self.label.setObjectName("label")
        self.gridLayout_2.addWidget(self.label, 0, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_5.setAlignment(QtCore.Qt.AlignCenter)
        self.label_5.setObjectName("label_5")
        self.gridLayout_2.addWidget(self.label_5, 0, 1, 1, 1)
        self.label_6 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_6.setAlignment(QtCore.Qt.AlignCenter)
        self.label_6.setObjectName("label_6")
        self.gridLayout_2.addWidget(self.label_6, 0, 2, 1, 1)
        self.label_7 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_7.setAlignment(QtCore.Qt.AlignCenter)
        self.label_7.setObjectName("label_7")
        self.gridLayout_2.addWidget(self.label_7, 0, 3, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_8.setAlignment(QtCore.Qt.AlignCenter)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 4, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_17.setAlignment(QtCore.Qt.AlignCenter)
        self.label_17.setObjectName("label_17")
        self.gridLayout_2.addWidget(self.label_17, 0, 5, 1, 1)
        self.label_19 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_19.setAlignment(QtCore.Qt.AlignCenter)
        self.label_19.setObjectName("label_19")
        self.gridLayout_2.addWidget(self.label_19, 0, 6, 1, 1)
        self.label_27 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_27.setAlignment(QtCore.Qt.AlignCenter)
        self.label_27.setObjectName("label_27")
        self.gridLayout_2.addWidget(self.label_27, 0, 7, 1, 1)
        self.label_28 = QtWidgets.QLabel(self.layoutWidget_5)
        self.label_28.setAlignment(QtCore.Qt.AlignCenter)
        self.label_28.setObjectName("label_28")
        self.gridLayout_2.addWidget(self.label_28, 0, 8, 1, 1)
        self.stackedWidget.addWidget(self.page_2)

        self.retranslateUi(Form)
        self.stackedWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_1.setText(_translate("Form", "模块型号："))
        self.label_2.setText(_translate("Form", "检测类型："))
        self.label_3.setText(_translate("Form", "硬件检测："))
        self.label_4.setText(_translate("Form", "错误警告："))
        self.label_Module_Type.setText(_translate("Form", "LX - XXXX"))
        self.label_Object_Type.setText(_translate("Form", "PT"))
        self.label_Hard_Detection_Code.setText(_translate("Form", "FFFF"))
        self.label_Error.setText(_translate("Form", "无错误"))
        self.label_35.setText(_translate("Form", "单位"))
        self.label_9.setText(_translate("Form", "CH 1"))
        self.label_20.setText(_translate("Form", "检测中..."))
        self.label_10.setText(_translate("Form", "CH 2"))
        self.label_18.setText(_translate("Form", "检测中..."))
        self.label_12.setText(_translate("Form", "CH 3"))
        self.label_21.setText(_translate("Form", "检测中..."))
        self.label_11.setText(_translate("Form", "CH 4"))
        self.label_22.setText(_translate("Form", "检测中..."))
        self.label_13.setText(_translate("Form", "CH 5"))
        self.label_23.setText(_translate("Form", "检测中..."))
        self.label_14.setText(_translate("Form", "CH 6"))
        self.label_24.setText(_translate("Form", "检测中..."))
        self.label_15.setText(_translate("Form", "CH 7"))
        self.label_25.setText(_translate("Form", "检测中..."))
        self.label_16.setText(_translate("Form", "CH 8"))
        self.label_26.setText(_translate("Form", "检测中..."))
        self.label.setText(_translate("Form", "  通道 ID"))
        self.label_5.setText(_translate("Form", "初始采样值"))
        self.label_6.setText(_translate("Form", "A 点校准"))
        self.label_7.setText(_translate("Form", "B 点校准"))
        self.label_8.setText(_translate("Form", "基准1检测"))
        self.label_17.setText(_translate("Form", "基准2检测"))
        self.label_19.setText(_translate("Form", "基准3检测"))
        self.label_27.setText(_translate("Form", "平均误差"))
        self.label_28.setText(_translate("Form", "校准结果"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())

