# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'widget_calibration_backstage_copy.ui'
#
# Created: Tue May  9 00:53:20 2017
#      by: PyQt5 UI code generator 5.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_widget_Calibration_Backstage(object):
    def setupUi(self, widget_Calibration_Backstage):
        widget_Calibration_Backstage.setObjectName("widget_Calibration_Backstage")
        widget_Calibration_Backstage.resize(842, 396)
        self.groupBox = QtWidgets.QGroupBox(widget_Calibration_Backstage)
        self.groupBox.setGeometry(QtCore.QRect(0, 8, 833, 377))
        self.groupBox.setTitle("")
        self.groupBox.setObjectName("groupBox")
        self.widget = QtWidgets.QWidget(self.groupBox)
        self.widget.setGeometry(QtCore.QRect(16, 16, 793, 249))
        self.widget.setObjectName("widget")
        self.gridLayout = QtWidgets.QGridLayout(self.widget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.label = QtWidgets.QLabel(self.widget)
        self.label.setObjectName("label")
        self.gridLayout.addWidget(self.label, 0, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(self.widget)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 1, 1, 1)
        self.label_9 = QtWidgets.QLabel(self.widget)
        self.label_9.setObjectName("label_9")
        self.gridLayout.addWidget(self.label_9, 1, 0, 1, 1)
        self.lineEdit_2 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.gridLayout.addWidget(self.lineEdit_2, 1, 1, 1, 1)
        self.lineEdit = QtWidgets.QLineEdit(self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.gridLayout.addWidget(self.lineEdit, 1, 2, 1, 2)
        self.lineEdit_3 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_3.setObjectName("lineEdit_3")
        self.gridLayout.addWidget(self.lineEdit_3, 1, 4, 1, 2)
        self.lineEdit_4 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_4.setObjectName("lineEdit_4")
        self.gridLayout.addWidget(self.lineEdit_4, 1, 6, 1, 2)
        self.lineEdit_5 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_5.setObjectName("lineEdit_5")
        self.gridLayout.addWidget(self.lineEdit_5, 1, 8, 1, 2)
        self.lineEdit_6 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.gridLayout.addWidget(self.lineEdit_6, 1, 10, 1, 2)
        self.lineEdit_7 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_7.setObjectName("lineEdit_7")
        self.gridLayout.addWidget(self.lineEdit_7, 1, 12, 1, 2)
        self.label_20 = QtWidgets.QLabel(self.widget)
        self.label_20.setObjectName("label_20")
        self.gridLayout.addWidget(self.label_20, 1, 14, 1, 1)
        self.label_10 = QtWidgets.QLabel(self.widget)
        self.label_10.setObjectName("label_10")
        self.gridLayout.addWidget(self.label_10, 2, 0, 1, 1)
        self.lineEdit_8 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_8.setObjectName("lineEdit_8")
        self.gridLayout.addWidget(self.lineEdit_8, 2, 1, 1, 1)
        self.lineEdit_15 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_15.setObjectName("lineEdit_15")
        self.gridLayout.addWidget(self.lineEdit_15, 2, 2, 1, 2)
        self.lineEdit_22 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_22.setObjectName("lineEdit_22")
        self.gridLayout.addWidget(self.lineEdit_22, 2, 4, 1, 2)
        self.lineEdit_23 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_23.setObjectName("lineEdit_23")
        self.gridLayout.addWidget(self.lineEdit_23, 2, 6, 1, 2)
        self.lineEdit_24 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_24.setObjectName("lineEdit_24")
        self.gridLayout.addWidget(self.lineEdit_24, 2, 8, 1, 2)
        self.lineEdit_45 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_45.setObjectName("lineEdit_45")
        self.gridLayout.addWidget(self.lineEdit_45, 2, 10, 1, 2)
        self.lineEdit_51 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_51.setObjectName("lineEdit_51")
        self.gridLayout.addWidget(self.lineEdit_51, 2, 12, 1, 2)
        self.label_18 = QtWidgets.QLabel(self.widget)
        self.label_18.setObjectName("label_18")
        self.gridLayout.addWidget(self.label_18, 2, 14, 1, 1)
        self.label_12 = QtWidgets.QLabel(self.widget)
        self.label_12.setObjectName("label_12")
        self.gridLayout.addWidget(self.label_12, 3, 0, 1, 1)
        self.lineEdit_9 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_9.setObjectName("lineEdit_9")
        self.gridLayout.addWidget(self.lineEdit_9, 3, 1, 1, 1)
        self.lineEdit_16 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_16.setObjectName("lineEdit_16")
        self.gridLayout.addWidget(self.lineEdit_16, 3, 2, 1, 2)
        self.lineEdit_34 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_34.setObjectName("lineEdit_34")
        self.gridLayout.addWidget(self.lineEdit_34, 3, 4, 1, 2)
        self.lineEdit_35 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_35.setObjectName("lineEdit_35")
        self.gridLayout.addWidget(self.lineEdit_35, 3, 6, 1, 2)
        self.lineEdit_40 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_40.setObjectName("lineEdit_40")
        self.gridLayout.addWidget(self.lineEdit_40, 3, 8, 1, 2)
        self.lineEdit_46 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_46.setObjectName("lineEdit_46")
        self.gridLayout.addWidget(self.lineEdit_46, 3, 10, 1, 2)
        self.lineEdit_52 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_52.setObjectName("lineEdit_52")
        self.gridLayout.addWidget(self.lineEdit_52, 3, 12, 1, 2)
        self.label_21 = QtWidgets.QLabel(self.widget)
        self.label_21.setObjectName("label_21")
        self.gridLayout.addWidget(self.label_21, 3, 14, 1, 1)
        self.label_11 = QtWidgets.QLabel(self.widget)
        self.label_11.setObjectName("label_11")
        self.gridLayout.addWidget(self.label_11, 4, 0, 1, 1)
        self.lineEdit_10 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_10.setObjectName("lineEdit_10")
        self.gridLayout.addWidget(self.lineEdit_10, 4, 1, 1, 1)
        self.lineEdit_21 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_21.setObjectName("lineEdit_21")
        self.gridLayout.addWidget(self.lineEdit_21, 4, 2, 1, 2)
        self.lineEdit_33 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_33.setObjectName("lineEdit_33")
        self.gridLayout.addWidget(self.lineEdit_33, 4, 4, 1, 2)
        self.lineEdit_20 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_20.setObjectName("lineEdit_20")
        self.gridLayout.addWidget(self.lineEdit_20, 4, 6, 1, 2)
        self.lineEdit_19 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_19.setObjectName("lineEdit_19")
        self.gridLayout.addWidget(self.lineEdit_19, 4, 8, 1, 2)
        self.lineEdit_18 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_18.setObjectName("lineEdit_18")
        self.gridLayout.addWidget(self.lineEdit_18, 4, 10, 1, 2)
        self.lineEdit_17 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_17.setObjectName("lineEdit_17")
        self.gridLayout.addWidget(self.lineEdit_17, 4, 12, 1, 2)
        self.label_22 = QtWidgets.QLabel(self.widget)
        self.label_22.setObjectName("label_22")
        self.gridLayout.addWidget(self.label_22, 4, 14, 1, 1)
        self.label_13 = QtWidgets.QLabel(self.widget)
        self.label_13.setObjectName("label_13")
        self.gridLayout.addWidget(self.label_13, 5, 0, 1, 1)
        self.lineEdit_11 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_11.setObjectName("lineEdit_11")
        self.gridLayout.addWidget(self.lineEdit_11, 5, 1, 1, 1)
        self.lineEdit_27 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_27.setObjectName("lineEdit_27")
        self.gridLayout.addWidget(self.lineEdit_27, 5, 2, 1, 2)
        self.lineEdit_32 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_32.setObjectName("lineEdit_32")
        self.gridLayout.addWidget(self.lineEdit_32, 5, 4, 1, 2)
        self.lineEdit_36 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_36.setObjectName("lineEdit_36")
        self.gridLayout.addWidget(self.lineEdit_36, 5, 6, 1, 2)
        self.lineEdit_41 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_41.setObjectName("lineEdit_41")
        self.gridLayout.addWidget(self.lineEdit_41, 5, 8, 1, 2)
        self.lineEdit_47 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_47.setObjectName("lineEdit_47")
        self.gridLayout.addWidget(self.lineEdit_47, 5, 10, 1, 2)
        self.lineEdit_53 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_53.setObjectName("lineEdit_53")
        self.gridLayout.addWidget(self.lineEdit_53, 5, 12, 1, 2)
        self.label_23 = QtWidgets.QLabel(self.widget)
        self.label_23.setObjectName("label_23")
        self.gridLayout.addWidget(self.label_23, 5, 14, 1, 1)
        self.label_14 = QtWidgets.QLabel(self.widget)
        self.label_14.setObjectName("label_14")
        self.gridLayout.addWidget(self.label_14, 6, 0, 1, 1)
        self.lineEdit_12 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_12.setObjectName("lineEdit_12")
        self.gridLayout.addWidget(self.lineEdit_12, 6, 1, 1, 1)
        self.lineEdit_26 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_26.setObjectName("lineEdit_26")
        self.gridLayout.addWidget(self.lineEdit_26, 6, 2, 1, 2)
        self.lineEdit_31 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_31.setObjectName("lineEdit_31")
        self.gridLayout.addWidget(self.lineEdit_31, 6, 4, 1, 2)
        self.lineEdit_37 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_37.setObjectName("lineEdit_37")
        self.gridLayout.addWidget(self.lineEdit_37, 6, 6, 1, 2)
        self.lineEdit_42 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_42.setObjectName("lineEdit_42")
        self.gridLayout.addWidget(self.lineEdit_42, 6, 8, 1, 2)
        self.lineEdit_48 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_48.setObjectName("lineEdit_48")
        self.gridLayout.addWidget(self.lineEdit_48, 6, 10, 1, 2)
        self.lineEdit_54 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_54.setObjectName("lineEdit_54")
        self.gridLayout.addWidget(self.lineEdit_54, 6, 12, 1, 2)
        self.label_24 = QtWidgets.QLabel(self.widget)
        self.label_24.setObjectName("label_24")
        self.gridLayout.addWidget(self.label_24, 6, 14, 1, 1)
        self.label_15 = QtWidgets.QLabel(self.widget)
        self.label_15.setObjectName("label_15")
        self.gridLayout.addWidget(self.label_15, 7, 0, 1, 1)
        self.lineEdit_13 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_13.setObjectName("lineEdit_13")
        self.gridLayout.addWidget(self.lineEdit_13, 7, 1, 1, 1)
        self.lineEdit_25 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_25.setObjectName("lineEdit_25")
        self.gridLayout.addWidget(self.lineEdit_25, 7, 2, 1, 2)
        self.lineEdit_30 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_30.setObjectName("lineEdit_30")
        self.gridLayout.addWidget(self.lineEdit_30, 7, 4, 1, 2)
        self.lineEdit_38 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_38.setObjectName("lineEdit_38")
        self.gridLayout.addWidget(self.lineEdit_38, 7, 6, 1, 2)
        self.lineEdit_43 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_43.setObjectName("lineEdit_43")
        self.gridLayout.addWidget(self.lineEdit_43, 7, 8, 1, 2)
        self.lineEdit_49 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_49.setObjectName("lineEdit_49")
        self.gridLayout.addWidget(self.lineEdit_49, 7, 10, 1, 2)
        self.lineEdit_55 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_55.setObjectName("lineEdit_55")
        self.gridLayout.addWidget(self.lineEdit_55, 7, 12, 1, 2)
        self.label_25 = QtWidgets.QLabel(self.widget)
        self.label_25.setObjectName("label_25")
        self.gridLayout.addWidget(self.label_25, 7, 14, 1, 1)
        self.label_16 = QtWidgets.QLabel(self.widget)
        self.label_16.setObjectName("label_16")
        self.gridLayout.addWidget(self.label_16, 8, 0, 1, 1)
        self.lineEdit_14 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_14.setObjectName("lineEdit_14")
        self.gridLayout.addWidget(self.lineEdit_14, 8, 1, 1, 1)
        self.lineEdit_28 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_28.setObjectName("lineEdit_28")
        self.gridLayout.addWidget(self.lineEdit_28, 8, 2, 1, 2)
        self.lineEdit_29 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_29.setObjectName("lineEdit_29")
        self.gridLayout.addWidget(self.lineEdit_29, 8, 4, 1, 2)
        self.lineEdit_39 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_39.setObjectName("lineEdit_39")
        self.gridLayout.addWidget(self.lineEdit_39, 8, 6, 1, 2)
        self.lineEdit_44 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_44.setObjectName("lineEdit_44")
        self.gridLayout.addWidget(self.lineEdit_44, 8, 8, 1, 2)
        self.lineEdit_50 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_50.setObjectName("lineEdit_50")
        self.gridLayout.addWidget(self.lineEdit_50, 8, 10, 1, 2)
        self.lineEdit_56 = QtWidgets.QLineEdit(self.widget)
        self.lineEdit_56.setObjectName("lineEdit_56")
        self.gridLayout.addWidget(self.lineEdit_56, 8, 12, 1, 2)
        self.label_26 = QtWidgets.QLabel(self.widget)
        self.label_26.setObjectName("label_26")
        self.gridLayout.addWidget(self.label_26, 8, 14, 1, 1)
        self.label_17 = QtWidgets.QLabel(self.widget)
        self.label_17.setObjectName("label_17")
        self.gridLayout.addWidget(self.label_17, 0, 14, 1, 1)
        self.label_8 = QtWidgets.QLabel(self.widget)
        self.label_8.setObjectName("label_8")
        self.gridLayout.addWidget(self.label_8, 0, 12, 1, 2)
        self.label_7 = QtWidgets.QLabel(self.widget)
        self.label_7.setObjectName("label_7")
        self.gridLayout.addWidget(self.label_7, 0, 10, 1, 2)
        self.label_6 = QtWidgets.QLabel(self.widget)
        self.label_6.setObjectName("label_6")
        self.gridLayout.addWidget(self.label_6, 0, 8, 1, 2)
        self.label_5 = QtWidgets.QLabel(self.widget)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 0, 6, 1, 2)
        self.label_4 = QtWidgets.QLabel(self.widget)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 0, 4, 1, 2)
        self.label_3 = QtWidgets.QLabel(self.widget)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 2, 1, 2)

        self.retranslateUi(widget_Calibration_Backstage)
        QtCore.QMetaObject.connectSlotsByName(widget_Calibration_Backstage)

    def retranslateUi(self, widget_Calibration_Backstage):
        _translate = QtCore.QCoreApplication.translate
        widget_Calibration_Backstage.setWindowTitle(_translate("widget_Calibration_Backstage", "Form"))
        self.label.setText(_translate("widget_Calibration_Backstage", "  通道 ID"))
        self.label_2.setText(_translate("widget_Calibration_Backstage", "当前采样"))
        self.label_9.setText(_translate("widget_Calibration_Backstage", "    CH 1    "))
        self.label_20.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_10.setText(_translate("widget_Calibration_Backstage", "    CH 2    "))
        self.label_18.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_12.setText(_translate("widget_Calibration_Backstage", "    CH 3    "))
        self.label_21.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_11.setText(_translate("widget_Calibration_Backstage", "    CH 4    "))
        self.label_22.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_13.setText(_translate("widget_Calibration_Backstage", "    CH 5    "))
        self.label_23.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_14.setText(_translate("widget_Calibration_Backstage", "    CH 6    "))
        self.label_24.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_15.setText(_translate("widget_Calibration_Backstage", "    CH 7    "))
        self.label_25.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_16.setText(_translate("widget_Calibration_Backstage", "    CH 8    "))
        self.label_26.setText(_translate("widget_Calibration_Backstage", "检测中..."))
        self.label_17.setText(_translate("widget_Calibration_Backstage", "校准结果"))
        self.label_8.setText(_translate("widget_Calibration_Backstage", "平均误差(℃)"))
        self.label_7.setText(_translate("widget_Calibration_Backstage", "R200检测(℃)"))
        self.label_6.setText(_translate("widget_Calibration_Backstage", "R150检测(℃)"))
        self.label_5.setText(_translate("widget_Calibration_Backstage", "R68 检测(℃)"))
        self.label_4.setText(_translate("widget_Calibration_Backstage", "B 点校准"))
        self.label_3.setText(_translate("widget_Calibration_Backstage", "A 点校准"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    widget_Calibration_Backstage = QtWidgets.QWidget()
    ui = Ui_widget_Calibration_Backstage()
    ui.setupUi(widget_Calibration_Backstage)
    widget_Calibration_Backstage.show()
    sys.exit(app.exec_())

